<p>
    <a href="<?php echo $this->url(array('controller'=>'about'), 'default', true) ?>"><img src="<?php echo $this->baseUrl() ?>/img/about-box-photo.jpg" alt="[Profile photo]" class="about-box-photo"></a>
    Hi! I'm Andrew, a Web devel&shy;oper and PHP prog&shy;rammer currently living in the south of England.
</p>

<p class="about-box-morelink">
    <a href="<?php echo $this->url(array('controller'=>'about'), 'default', true) ?>">Want to know more?</a>
</p>
