<p>
    <a href="<?php echo $this->url(array('controller'=>'about'), 'default', true) ?>"><img src="<?php echo $this->baseUrl() ?>/img/about-box-photo.jpg" alt="[Profile photo]" class="about-box-photo"></a>
    Hi! I'm Andrew, a Web devel&shy;oper and PHP prog&shy;rammer currently living in the south of England.
</p>

<p class="about-box-morelink">
    <a href="<?php echo $this->url(array('controller'=>'about'), 'default', true) ?>">Want to know more?</a>
</p>

<?php if (Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('lookingForWork')): ?>
    <p>I'm available for full-time, permanent work as an experienced, Zend Certified, Web Developer! Interested? <a href="mailto:cv@andrewgillard.com">Email me</a>, or <a href="<?php echo $this->url(array('controller'=>'cv'), 'default', true) ?>">see my CV</a> or <a href="<?php echo $this->url(array('controller'=>'portfolio'), 'default', true) ?>">portfolio</a>.</p>
<?php endif; ?>