<ul class="github">
    <li class="sprite-sites-php"><a href="https://github.com/aziraphale/AndrewGillard.com">This website!</a></li>
    <li class="sprite-sites-html"><a href="https://github.com/aziraphale/Furcode-Generator">Furcode Generator</a></li>
    <li class="sprite-sites-php"><a href="https://github.com/aziraphale/Image-De-duplicator">Image De-Duplicator</a></li>
    <li class="sprite-sites-html5"><a href="https://github.com/aziraphale/Location-for-IRC">Location for IRC</a></li>
    <li class="sprite-sites-php"><a href="https://github.com/aziraphale/PHP-IRC-Modules">PHP-IRC Modules</a></li>
    <li class="sprite-sites-java github-fork" title="This is my fork of Sandsmark's project"><a href="https://github.com/aziraphale/QuasselDroid">QuasselDroid</a></li>
    <li class="sprite-sites-php"><a href="https://github.com/aziraphale/Router-Log-Check">Router Log Check</a></li>
    <li class="sprite-sites-html5"><a href="https://github.com/aziraphale/Shopping-List">Shopping List</a></li>
    <li class="sprite-sites-php"><a href="https://github.com/aziraphale/Simple-Gallery">Simple Gallery</a></li>
    <li class="sprite-sites-php"><a href="https://github.com/aziraphale/Unwatched-TV">Unwatched TV</a></li>
</ul>