<ul class="sites">
    <li>
        <strong>Code, Work, etc.</strong>
        <ul>
            <li class="sprite-sites-github"><a href="https://github.com/aziraphale" title="GitHub">GitHub</a></li>
            <li class="sprite-sites-stackexchange"><a href="http://stackexchange.com/users/196474/aziraphale" title="Stack Exchange">Stack Exchange</a></li>
            <li class="sprite-sites-wikipedia"><a href="http://en.wikipedia.org/wiki/Special:Contributions/Lord_d%27Eath" title="Wikipedia">Wikipedia</a></li>
            <li class="sprite-sites-zce"><a href="http://www.zend.com/en/yellow-pages#show-ClientCandidateID=ZEND014075" title="PHP Yellow Pages entry">Zend Certified Engineer</a></li>
            <li class="sprite-sites-cbsys"><a href="http://www.craigbrasssystems.com/forum/user/5-andrew-gillard/" title="Craig Brass Systems Forum">Work Forum Account</a></li>
        </ul>
    </li>
    <li>
        <strong>My Other Sites</strong>
        <ul>
            <li class="sprite-sites-dwpriests"><a href="http://www.dwpriests.com/wiki/Main_Page" title="Discworld MUD Priests Guild Wiki">DW MUD Priests Wiki</a></li>
            <li class="sprite-sites-misc"><a href="http://www.web2messenger.com/" title="Web2Messenger">Web2Messenger</a></li>
            <li class="sprite-sites-misc"><a href="http://www.udcx.com/" title="Unofficial Dark Century: X [Neverwinter Nights persistent world &quot;fansite&quot;]">uDCX</a></li>
        </ul>
    </li>
    <li>
        <strong>Gaming</strong>
        <ul>
            <li class="sprite-sites-steam"><a href="http://steamcommunity.com/id/lorddeath/" title="Steam">Steam</a></li>
            <li class="sprite-sites-xbl"><a href="http://live.xbox.com/en-GB/Profile?gamertag=Zweiblumen" title="Xbox Live">Xbox Live</a></li>
        </ul>
    </li>
    <li>
        <strong>Photography</strong>
        <ul>
            <li class="sprite-sites-twitpic"><a href="http://twitpic.com/photos/lorddeath" title="Twitpic">Twitpic</a></li>
            <li class="sprite-sites-flickr"><a href="http://www.flickr.com/photos/lorddeath/" title="Flickr">Flickr</a></li>
            <li class="sprite-sites-youtube"><a href="http://www.youtube.com/user/aziraphale87" title="YouTube">YouTube</a></li>
        </ul>
    </li>
    <li>
        <strong>Social</strong>
        <ul>
            <li class="sprite-sites-lastfm"><a href="http://www.last.fm/user/Aziraphale87" title="Last.fm">Last.fm</a></li>
            <li class="sprite-sites-facebook"><a href="https://www.facebook.com/andrewgillard" title="Facebook">Facebook</a></li>
            <li class="sprite-sites-gplus"><a href="https://plus.google.com/u/0/115534677554080904530" title="Google+">Google+</a></li>
            <li class="sprite-sites-linkedin"><a href="http://www.linkedin.com/profile/view?id=174298547" title="LinkedIn">LinkedIn</a></li>
            <li class="sprite-sites-twitter"><a href="https://twitter.com/lorddeath" title="Twitter">Twitter</a></li>
            <li class="sprite-sites-foursquare"><a href="https://foursquare.com/lorddeath" title="Foursquare">Foursquare</a></li>
            <li class="sprite-sites-fuelly"><a href="https://www.fuelly.com/driver/lorddeath" title="Fuelly">Fuelly</a></li>
            <li class="sprite-sites-messbe"><a href="http://forum.mess.be/index.php?showuser=4988" title="Mess.be Forum">Mess.be Forum</a></li>
            <li class="sprite-sites-nusphere"><a href="http://forum.nusphere.com/member3508.html" title="NuSphere Forum">NuSphere Forum</a></li>
            <li class="sprite-sites-msghelp"><a href="http://msghelp.net/member.php?action=profile&amp;uid=2935" title="Messenger Plus! Forum">Messenger Plus! Forum</a></li>
        </ul>
    </li>
</ul>