<article>
    <p>The following is a comprehensive list of Mishal's deaths.</p>
</article>

<article>
<p class="dwquote"><a id="death1" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
You enter the flame, feeling perfectly at one with Sek for a moment before you suddenly find yourself elsewhere.
The centre of the Royal Market <span class="dwq_green">[n,s,e,w]</span>.
A hairy bum and a pie seller are standing here.
A wooden pole with a bright blue note and a silver note attached to it is standing on the side of the road, three pumpkins and a medium sized mauve bottle are on the ground and a lamp post is here, lighting up the street.
For a moment you feel like skipping, but it passes.
You remove the flat cap.
The suspicious character moves slowly out of the shadows.
You carefully attach the diamond Berilia charm to the gold charm bracelet.
The suspicious character sidles up to you ingratiatingly.
<span class="dwq_cyan">The suspicious character asks you with a Sto Plains accent: Evening mister. Fancy a good time?</span>
The suspicious character peers at you, grinning disarmingly.
The suspicious character grins darkly.
The suspicious character attacks you from behind.  You recall him standing right in front of you just a second ago.
You are shocked and confused.
Moving swiftly, the suspicious character slices your right leg with his meat cleaver.
With surprising speed, the suspicious character hacks your chest with his cheap and nasty switchblade.
Catching you by surprise, the suspicious character slices your left foot with his cheap and nasty switchblade.
<span class="dwq_boldyellow">Hp: 742 (1503) Gp: 79 (325) Xp: 11291</span>
The suspicious character slices your right arm with his meat cleaver.
<span class="dwq_boldyellow">Hp: 588 (1428) Gp: 79 (315) Xp: 11294</span>
The suspicious character shoves you sending you crashing to the ground.
<span class="dwq_boldyellow">Hp: 591 (1428) Gp: 82 (315) Xp: 11297</span>
The suspicious character cuts your chest with his meat cleaver.
The suspicious character cuts your left arm with his cheap and nasty switchblade.
<span class="dwq_boldyellow">Hp: 404 (1428) Gp: 85 (315) Xp: 11300</span>
The suspicious character cuts your back with his meat cleaver.
<span class="dwq_boldred">Hp: 317 (1428) Gp: 88 (315) Xp: 11303</span>
You stand up.
<span class="dwq_boldred">Hp: 320 (1428) Gp: 91 (315) Xp: 11306</span>
The suspicious character launches a powerful attack.  The suspicious character hacks your chest with his meat cleaver.
You no longer feel shocked and confused.
The suspicious character gets 11 Djelian talents, 10 Lancre shillings, 6 Ankh-Morpork pence, one Ankh-Morpork royal, some Ankh-Morpork dollars, 9 Lancre crowns, one Lancre farthing, 8 Ankh-Morpork ten-dollars, 5 Agatean Empire rhinu, 2 Ankh-Morpork ten-pences, 5 Genuan livres and some Genuan cents from the corpse of Mishal d'Ranged.
Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?  SHALL WE POPPADOM TO THE NEXT DIMENSION?
You turn and see Death standing behind you.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<article>
<p class="dwquote"><a id="death2" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
A road <span class="dwq_green">[n,w,e]</span>.
An old villager is standing here.
A small wooden numberplate is on the north wall and a wooden pole with an olive note and a white note attached to it is here.
<span class="dwq_typed">sb</span>
Hp: 1503(1503)  Gp: 183(349)  Xp: 1578285
&gt;  <span class="dwq_typed">s</span>

AAARRRGGGHHH!!!

An air room <span class="dwq_green">[none]</span>.
&gt;  <span class="dwq_typed">tbr</span>
You can't concentrate enough to twist the blue crystal ring.
&gt;  <span class="dwq_boldred">You find it hard to float and make a quick trip thirty-five yards downwards.</span>
Some moorland close to a mountain range and an evergreen forest <span class="dwq_green">[n,climb e,climb s]</span>.
<span class="dwq_boldred">Ouch, that hurt (1786).</span>
<span class="dwq_cyan">Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?  SHALL WE POPPADOM TO THE NEXT DIMENSION?</span>
You turn and see Death standing behind you.
<span class="dwq_cyan">Death says: PERHAPS YOU SHOULD TAKE A NUMBER,  WE ARE BUSY TODAY.</span>
<span class="dwq_cyan">Death says: THE GODS ALWAYS SEEM TO LET PEOPLE LIKE YOU HAVE ANOTHER CHANCE BUT I DON'T SEE THE POINT.</span>
<span class="dwq_cyan">Death says: I SUPPOSE YOU WANT TO BE ALLOWED TO STAY, DO YOU?</span>
<span class="dwq_cyan">Death says: I REALLY DON'T LIKE DOING ALL THESE FAVOURS FOR YOU PEOPLE.</span>
<span class="dwq_cyan">Death says: I MEAN, WHAT'S IN IT FOR ME?</span>
<span class="dwq_cyan">Death says: OH DEAR, IT SEEMS SEK WON'T SEE YOU RIGHT NOW.</span>
<span class="dwq_cyan">Death says: JUST DON'T TELL ANYONE I DID THIS FOR YOU!</span>
<span class="dwq_cyan">Death says: I MAY NOT BE SO FORGIVING IN THE FUTURE.  BE MORE CAREFUL.</span>
<span class="dwq_cyan">Death gets back onto Binky and rides away.</span>
You hear a pattering of many tiny feet.
The ground suddenly opens up in front of your feet and a bunch of manically grinning dwarfs pop out and start
bouncing around in front of you.
<span class="dwq_cyan">With a huge smile one of the grinning dwarfs whispers in your ear: Here, take this book - it'll tell you everything you need to know.  But don't mention it to Death.  Ok?</span>
Without waiting, they all leap back into the hole which slowly closes after them.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<article>
<p class="dwquote"><a id="death3" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
<span class="dwq_typed">t cal Just find a tree to climb and TM!
</span><span>You exclaim to Cal: Just find a tree to climb and TM!
</span><span>&gt; <span class="dwq_typed">eggtree</span>
</span><span>You remove a silver book charm from Brass Bracelet.
</span><span>It seems easier to perform divine hand because you are near holy ground.
</span><span>Queued command: enter flame
</span><span>Queued command: add silver book charm to brass bracelet
</span><span>&gt; You say a prayer over a silver book charm.
</span><span>You attempt to visualise the place that you remembered.
</span><span>You pray to Sek to grant you the means to travel there.
</span><span>You meditate on the holiness of Sek before vanishing.
</span><span>[Sek's chamber]
</span><span>    </span><span class="dwq_boldyellow">@</span><span>     
</span><span>You seem to be on a roughly circular island of black stone in the middle of a sea of flames and bubbling lava.  Thankfully the island is large, otherwise the heat would be unbearable and even the most devout Sekkites' barbed wire underwear would leave scorch marks against the skin after a few moments of being here.  The island is featureless, except for a slight depression in the centre where a small statue of Sek lies.  A large flame dances in the air above His effigy.
</span><span class="dwq_green">There are no obvious exits.
</span><span class="dwq_boldyellow"><u>Cal</u> tells you: You say that like it's easy :P
</span><span>You enter the flame, feeling perfectly at one with Sek for a moment before you suddenly find yourself elsewhere.
</span><span>[by the base of a giant pine, where the forest thins out]
</span><span>    </span><span class="dwq_boldyellow">@</span><span>     
</span><span>   /      
</span><span> -</span><span class="dwq_cyan">*</span><span>       
</span><span>The trail dips here as it moves down a ridge of the hill, giving the impression that many of the surrounding trees are taller than is really the case.  One, however, needs no exaggeration: a giant pine towers in front and to your right, soaring above the treetops and dominating the surrounding forest.  Behind you and to your right the trees thin out as the trail climbs the spur of the hill, while on all other sides it grows thicker in the deeper soil.
</span><span class="dwq_yellow">It is a very warm autumn prime's midday with almost no wind and a few high level cirrus clouds.
</span><span class="dwq_green">There is one obvious exit: <u>southwest</u>.
</span><span>A pair of vampire fangs, a closed small brown book, a plain linen corset, a fluffy pink towel, a half-pint glass and a small knife are on the ground.
</span><span>You carefully attach the silver book charm to Brass Bracelet.
<span class="dwq_typed">climb tree</span>
</span><span>Saving...
</span><span class="dwq_boldyellow">With all your climbing, you discover you've found a better way to locate handholds.
</span><span>You leap lithely up onto a tall root and catch one of the lower branches, swinging yourself up into the towering pine tree.
</span><span>[lower branches of a large pine tree]
</span><span>    </span><span class="dwq_boldyellow">@</span><span>     
</span><span>Broad boughs and a mess of grey twigs conspire to obscure one's vision, here among the lowest branches of a giant forest pine.  The path below is visible, curving around the base of the tree, but on all sides and overhead nothing can be seen but pine innards.
</span><span class="dwq_yellow">It is a very warm autumn prime's midday with almost no wind and a few high level cirrus clouds.
</span><span class="dwq_green">There are no obvious exits.
</span><span>&gt; <span class="dwq_typed">t cal I just did it :P</span>
</span><span>You tell Cal: I just did it :P
<span class="dwq_typed">climb up</span>
</span><span>You scramble agilely from branch to branch up the tree.
</span><span>[halfway up a large pine tree]
</span><span>    </span><span class="dwq_boldyellow">@</span><span>     
</span><span>Halfway up this venerable pine tree, the broad boughs are still sturdy enough to be reliable, and the needles plentiful enough to conceal much of the view.  A pity, because this forest giant rises well above its fellows at its peak, and even here is high enough to see something of the surrounding treetops.
</span><span class="dwq_yellow">It is a very warm autumn prime's midday with almost no wind and a few high level cirrus clouds.
</span><span class="dwq_green">There are no obvious exits.
</span><span>&gt; <span class="dwq_typed">climb up</span>
</span><span>You scramble agilely from branch to branch up the tree.
</span><span>[lofty perch in a giant pine]
</span><span>    </span><span class="dwq_boldyellow">@</span><span>     
</span><span>Towering high above the surrounding treetops, the upper branches of this giant pine tree sway perilously backwards and forth with the wind.  Above this position, the branches are too thin to be climbed, and here their sparseness affords little protection from the elements - or from the results of an injudicious move.
</span><span class="dwq_yellow">It is a very warm autumn prime's midday with almost no wind and a few high level cirrus clouds.
</span><span class="dwq_green">There are no obvious exits.
</span><span>&gt; <span class="dwq_typed">climb d</span>
</span><span>You begin to climb but wobble precariously and decide to stay put for the moment.
</span><span>&gt; <span class="dwq_typed">climb d</span>
</span><span>You begin to climb but wobble precariously and decide to stay put for the moment.
</span><span>&gt; <span class="dwq_typed">climb d</span>
</span><span>You begin to climb but wobble precariously and decide to stay put for the moment.
</span><span>&gt; <span class="dwq_typed">climb d</span>
</span><span>You begin to climb but wobble precariously and decide to stay put for the moment.
</span><span>&gt; <span class="dwq_typed">climb d</span>
</span><span>You begin to climb but wobble precariously and decide to stay put for the moment.
</span><span>&gt; <span class="dwq_typed">climb d</span>
</span><span>You begin to climb, but your fatigue makes you clumsily lose your grip.
</span><span>[by the base of a giant pine, where the forest thins out]
</span><span>    </span><span class="dwq_boldyellow">@</span><span>     
</span><span>   /      
</span><span> -</span><span class="dwq_cyan">*</span><span>       
</span><span>The trail dips here as it moves down a ridge of the hill, giving the impression that many of the surrounding trees are taller than is really the case.  One, however, needs no exaggeration: a giant pine towers in front and to your right, soaring above the treetops and dominating the surrounding forest.  Behind you and to your right the trees thin out as the trail climbs the spur of the hill, while on all other sides it grows thicker in the deeper soil.
</span><span class="dwq_yellow">It is a very warm autumn prime's afternoon with almost no wind and scattered puffy clouds.
</span><span class="dwq_green">There is one obvious exit: <u>southwest</u>.
</span><span>A pair of vampire fangs, a closed small brown book, a plain linen corset, a fluffy pink towel, a half-pint glass and a small knife are on the ground.
</span><span>You stand up.
</span><span>You hit the ground with a sickening crunch.
</span><span class="dwq_red">Hp: 0 (1837) Gp: 171 (390) Xp: 7746
</span><span class="dwq_cyan">Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?  SHALL WE POPPADOM TO THE NEXT DIMENSION?
</span><span>You turn and see Death standing behind you.
</span><span class="dwq_cyan">Death says: AH, THERE YOU ARE.  ARE YOU THE LAST ONE?
</span><span class="dwq_cyan">Death says: ALAS, YOU ARE DEAD NOW:  SHUFFLED OFF THE MORTAL COIL, OUT OUT BRIEF CANDLE, FAREWELL CRUEL WORLD...
</span><span class="dwq_cyan">Death pauses for dramatic effect.  He's trying to humanise a touch.
</span><span class="dwq_cyan">Death says: I SUPPOSE YOU WANT TO BE ALLOWED TO STAY, DO YOU?
</span><span class="dwq_cyan">Death says: I REALLY DON'T LIKE DOING ALL THESE FAVOURS FOR YOU PEOPLE.
</span><span class="dwq_cyan">Death says: I MEAN, WHAT'S IN IT FOR ME?
</span><span class="dwq_cyan">Death says: SEK JUST SLIPPED ME A FIFTY TO LET YOU HAVE ANOTHER GO.  HMM...
</span><span class="dwq_cyan">Death says: JUST DON'T TELL ANYONE I DID THIS FOR YOU!
</span><span class="dwq_cyan">Death says: ARE YOU STILL HERE FOR ANY PARTICULAR REASON?  I HAVE BEEN KNOWN TO CHANGE MY MIND...
</span><span class="dwq_cyan">Death gets back onto Binky and rides away.</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Third death.  This time at the hands of a tree, though I think Rincewind would blame the ground.</p>
</article>

<article>
<p class="dwquote"><a id="death4" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
A Coffee Nostra hitman steps out of the shadows.
The Coffee Nostra hitman attacks you from behind.  You recall him standing right in front of you just a second ago.
You feel somewhat confused.
Striking like a cobra, the Coffee Nostra hitman chops up your chest with his long sword.
Moving too fast to see, the Coffee Nostra hitman pierces your neck with his no. 9 throwing knife.
In the blink of an eye, the Coffee Nostra hitman hacks your right leg with his long sword.
Moving too fast to see, the Coffee Nostra hitman hacks your left arm with his no. 9 throwing knife.
<span class="dwq_cyan">The Coffee Nostra hitman asks with a Genuan accent: You do not go against the family, capiche?</span>
The Coffee Nostra hitman melts into the shadows.

You no longer feel shocked and confused.
For a moment you feel like skipping, but it passes.
<span class="dwq_cyan">Death rides in and from Binky's back says: I'LL BE BACK SOON FOR YOU!</span>
<span class="dwq_cyan">Death charges off into the distance.</span>
<span class="dwq_cyan">Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?  SHALL WE POPPADOM TO THE NEXT DIMENSION?</span>
You turn and see Death standing behind you.
<span class="dwq_cyan">Death says: PERHAPS YOU SHOULD TAKE A NUMBER,  WE ARE BUSY TODAY.</span>
<span class="dwq_cyan">Death says: DON'T MAKE THOSE PUPPY DOG EYES, IT WON'T DO YOU ANY GOOD.</span>
<span class="dwq_cyan">Death says: I SUPPOSE YOU WANT TO BE ALLOWED TO STAY, DO YOU?</span>
<span class="dwq_cyan">Death says: I REALLY DON'T LIKE DOING ALL THESE FAVOURS FOR YOU PEOPLE.</span>
<span class="dwq_cyan">Death says: I MEAN, WHAT'S IN IT FOR ME?</span>
<span class="dwq_cyan">Death says: SEK JUST SLIPPED ME A FIFTY TO LET YOU HAVE ANOTHER GO.  HMM...</span>
<span class="dwq_cyan">Death says: IF YOU TALK ABOUT THIS TO ANYONE, WATCH OUT, YOU MAY JUST WAKE UP DEAD.</span>
<span class="dwq_cyan">Death says: I MAY NOT BE SO FORGIVING IN THE FUTURE.  BE MORE CAREFUL.</span>
<span class="dwq_cyan">Death gets back onto Binky and rides away.</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<article>
<p class="dwquote"><a id="death5" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
You feel a mild twinge in one knee.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
You feel a mild twinge in one knee.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
You feel a mild twinge in one knee.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
You feel a sharp stabbing pain at the base of your spine.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
You feel a sharp stabbing pain at the base of your spine.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
Your eyes bulge and you gasp with the pain exploding in every joint of your hands.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
Your eyes bulge and you gasp with the pain exploding in every joint of your hands.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
Your whole body goes rigid with the thunderous detonation of pain that takes place as you try to move.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
Brother Aulularia suddenly appears from within a bright orange flame which dissipates as quickly as it arrived.
Aulularia pets you.
Brother Aulularia grins.
Brother Aulularia looks at you.
Aulularia eeks at you.
Your whole body goes rigid with the thunderous detonation of pain that takes place as you try to move.
Your joints seem to be getting more inflamed.
Maybe it's something you're wearing?
For a moment you feel like skipping, but it passes.
Brother Aulularia sighs.
Brother Aulularia looks at you.
Brother Aulularia looks at you.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: You're dead :P</span>
Brother Aulularia leaves west.
Aulularia sighs at you.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Idiot :p</span>
<span class="dwq_boldyellow"><u>Aulularia</u> asks you: WAnt me to raise?</span>
Aulularia prods you.
<span class="dwq_typed">i</span>
You are just a disembodied spirit.  You have mist; what else do you want?
<span class="dwq_typed">t Aulularia Rofl</span>
You tell Aulularia: Rofl
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Fool.
<span class="dwq_typed">t Aulularia yeah :P</span></span>
You tell Aulularia: yeah :P
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: I saw you were in bad shape,but i didn't see you wearing it :P</span>
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: otherwise i would have healed :(</span>
Aulularia apologises to you.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Not properly dead either.</span>
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: you're not a ghost :P</span>
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: bit odd :P</span>
<span class="dwq_typed">l me</span>
Looking at yourself again?  What a narcissist!
You see Holy Mishal d'Ranged the Penitentiary of Sek.
He is a strapping young human lad.
As you glance at him you see his eyes as a deep red colour, however upon closer inspection they seem to be impossibly black and infinitely deep. The rest of his body is distinctly non-descript and within moments you all but forget your encounter with him. The veins on his face are very pronounced and a deep blue-black hue. His hair is short and jet-black. His fingers are extremely thin, his bones visible through the skin.
He appears to be dead.
He is standing.
He .
<span class="dwq_typed">t Aulularia Ooherr</span>
You tell Aulularia: Ooherr
<span class="dwq_typed">t Aulularia I'll find someone to res :P</span>
You tell Aulularia: I'll find someone to res :P
<span class="dwq_typed">sb</span>
You are just a disembodied spirit.  What use does a wispy thing like you have for a collection of meaningless numbers?
<span class="dwq_typed">qwho</span>
<span class="dwq_white">5 Creators:</span> Gin(<span class="dwq_red">D</span>) Sojan(<span class="dwq_boldred">T</span>) Thoreksken(<span class="dwq_boldcyan">S</span>) Touchstone(<span class="dwq_cyan">C</span>) Turvity(<span class="dwq_boldcyan">S</span>)
<span class="dwq_white">1 Playtester:</span> Clio
<span class="dwq_green">7 Friends:</span> Aulularia(<span class="dwq_green">F</span>) Comatsu(<span class="dwq_green">F</span>) Cthulhu(<span class="dwq_green">F</span>) Frey(<span class="dwq_green">F</span>) Mishal(<span class="dwq_green">F</span>) Thirsha(<span class="dwq_green">F</span>) Varthia(<span class="dwq_green">F</span>)
<span class="dwq_white">101 Players:</span> Aardwolf Adamantis Aduwen Allison Asha Aurethius Ayesha Barbosa Boba Bogtrot Bonkers Bontos Braff Calcium Catalysis Catherine Chaddice Cheeky Cure Danduin DeaLiuS Deva Earraich eep Eida EvenSong Eviscerator Faceless Fackos Fatin Feef Floppy Flounder Gidi Gigante Gouzz Grad Grimrak Helfire Hurry Ida Ilidus Itseybitsey Jeanie Kadense Kagemusha Kaijin Kankuro Kaula Klaz Kloke Klowtchly Koofle Leth Liameria Liard Locksley Lokinash Lyna Maelin Magus Malady Manacra Moraless Muni Myr Nikita Numbbum PozPaws Quotid Qwertz rebbaN Reed Rhalelden Rissa Rykoren Sadness Sevelille Shuwie Silverthorne Sined SoulForge Spanka Sulic sYc Taepha Talic Talven Teffa Thunder Tiala Tillen Tomorrow Trident Twiddle Velnia Viresan Wallace Wallsy Wayland Wotan
<span class="dwq_white">109 Players, 114 Total</span>
<span class="dwq_typed">l</span>
[Tuna Walk commercial area]
    <span class="dwq_red">+</span>    
<span class="dwq_cyan">&amp;</span>-<span class="dwq_cyan">@</span>-<span class="dwq_boldyellow">@</span>-<span class="dwq_cyan">*</span>-<span class="dwq_cyan">*</span>
  |   |  
About halfway along Tuna Walk, this part of the docks looks south across the ocean and Bes Pelargic's harbour.  Tuna Walk runs east and west along the harbour and beyond.  The harbour is crammed with boats of all shapes and sizes and people milling around, pursuing their daily business, or at least someone's daily business, whichever is the most interesting.  To the east Tuna Walk goes through an ornate archway.
There is a doorway in the north wall leading into a curious shop.
<span class="dwq_yellow">It is a very cold backspindlewinter's morning with a steady breeze, dense cloud cover and light snow.</span>
<span class="dwq_green">There are three obvious exits: <u>east</u>, <u>west</u> and <u>north</u>.</span>
A rickshaw driver is pulling the rickshaw along.
An enamelled sign is on the building and a rickshaw is here being pulled by the rickshaw driver.
<span class="dwq_typed">t Aurethius Uh, so where's my stuff gone?</span>
You ask Aurethius: Uh, so where's my stuff gone?
<span class="dwq_boldyellow"><u>Aurethius</u> tells you: Don't know what you're talking about.</span>
<span class="dwq_typed">t Aurethius Well I don't see anyone having moved it... it just... doesn'te xist</span>
You tell Aurethius: Well I don't see anyone having moved it... it just... doesn'te xist
<span class="dwq_typed">liaisons</span>
There are no Liaison creators currently logged on.
<span class="dwq_boldyellow"><u>Aurethius</u> asks you: What?</span>
<span class="dwq_typed">t Aurethius I'm dead, right? So surely I should have a CORPSE...?</span>
You ask Aurethius: I'm dead, right? So surely I should have a CORPSE...?
<span class="dwq_typed">wd</span>
--------------------------------------------==========]  Discworld  [===========--------------------------------------------
Holy Mishal d'Ranged the Penitentiary of Sek, <span class="dwq_yellow">Taxi:</span> <span class="dwq_red">Off (AFK)</span>
------------------------------There is one member of this group of people on the Discworld. &lt;-----------------------------
<span class="dwq_boldyellow"><u>Aurethius</u> asks you: Why are you asking me about this?</span>
<span class="dwq_typed">t Aurethius Uh beacuse tab-completion hit the wrong name :/ Curses. Sorry.</span>
You tell Aurethius: Uh beacuse tab-completion hit the wrong name :/ Curses. Sorry.
<span class="dwq_typed">blush Aurethius</span>
You blush at Aurethius.
<span class="dwq_boldyellow"><u>Aurethius</u> tells you: No biggie.</span>
<span class="dwq_typed">t Aulularia Okay so I've been talking to Aurethius instead of you for the past five minutes.</span>
You tell Aulularia: Okay so I've been talking to Aurethius instead of you for the past five minutes.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: :P</span>
Aulularia sniggers at you.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Fool :P</span>
<span class="dwq_typed">t Aulularia Anyway. Where the fsck is my corpse?</span>
You ask Aulularia: Anyway. Where the fsck is my corpse?
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: You're not dead :P</span>
<span class="dwq_typed">t Aulularia &quot;who dead&quot;, &quot;score brief&quot;, and &quot;inventory&quot; disgree with you, there :P</span>
You tell Aulularia: &quot;who dead&quot;, &quot;score brief&quot;, and &quot;inventory&quot; disgree with you, there :P
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Might be buggy. might be a feature :P</span>
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: you still have your inventory.</span>
Brother Aulularia suddenly appears from within a bright orange flame which dissipates as quickly as it arrived.
Brother Aulularia looks at you.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Oooooer.</span>
<span class="dwq_typed">t Aulularia Though yes, &quot;l me&quot; is dodgy.</span>
You tell Aulularia: Though yes, &quot;l me&quot; is dodgy.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: I can't see it eithe r:P
<span class="dwq_typed">l me</span></span>
Looking at yourself again?  What a narcissist!
You see Holy Mishal d'Ranged the Penitentiary of Sek.
He is a strapping young human lad.
As you glance at him you see his eyes as a deep red colour, however upon closer inspection they seem to be impossibly black and infinitely deep. The rest of his body is distinctly non-descript and within moments you all but forget your encounter with him. The veins on his face are very pronounced and a deep blue-black hue. His hair is short and jet-black. His fingers are extremely thin, his bones visible through the skin.
He appears to be dead.
He is standing.
<span class="dwq_boldyellow"><u>Aulularia</u> exclaims to you: Woo!</span>
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Get a creator to help you :P</span>
Brother Aulularia looks at you.
<span class="dwq_typed">t Aulularia When I looked at myself earlier I got: He appears to be dead. He is standing. He .</span>
You tell Aulularia: When I looked at myself earlier I got: He appears to be dead. He is standing. He .
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: Or see what happens when you get ressed
<span class="dwq_typed">sob</span></span>
You sob quietly.
Aulularia comforts you.
<span class="dwq_typed">t Touchstone Hey, I realise you're not a liaison, but are you able to help me, here? I stupidly left my flat cap on while going AFK, and now I'm &quot;dead&quot; but without a corpse... &quot;who dead&quot;, &quot;score brief&quot; and &quot;inventory&quot; claim I'm dead, but I don't appear to be a ghost, and looking at me has no idea what's going on...</span>
Touchstone has been idle for 3 minutes and 44 seconds.
You tell Touchstone: Hey, I realise you're not a liaison, but are you able to help me, here? I stupidly left my flat cap on while going AFK, and now I'm &quot;dead&quot; but without a corpse... &quot;who dead&quot;, &quot;score brief&quot; and &quot;inventory&quot; claim I'm dead, but I don't appear to be a ghost, and looking at me has no idea what's going on...
<span class="dwq_boldyellow"><u>Aulularia</u> asks you: getting a res, or are you talking to a cre?</span>
<span class="dwq_boldyellow"><u>Touchstone</u> tells you: Oh, dear. Let's see.</span>
<span class="dwq_typed">t Aulularia Asking Touchstone =/</span>
You tell Aulularia: Asking Touchstone =/
Aulularia grins at you.
<span class="dwq_typed">t Aulularia Never a liaison online when I need one :P</span>
Touchstone squeezes out of a hole that appears in midair.
You tell Aulularia: Never a liaison online when I need one :P
Touchstone looks at you.
Aulularia nods at you.
<span class="dwq_typed">smile Touchstone</span>
You smile at Touchstone.
Brother Aulularia sits down.
<span class="dwq_typed">t Touchstone The first time I looked at myself I got: He appears to be dead. He is standing. He .</span>
You tell Touchstone: The first time I looked at myself I got: He appears to be dead. He is standing. He .
<span class="dwq_boldyellow"><u>Touchstone</u> tells you: With luck, an expert will be able to sort things out.
<span class="dwq_typed">cheer</span></span>
You cheer enthusiastically.
Brother Aulularia looks at you.
<span class="dwq_typed">:really hopes this hasn't lost him all of his faith rods and remembers... Everything else is easily replacable... :S</span>
You emote: Mishal d'Ranged really hopes this hasn't lost him all of his faith rods and remembers... Everything else is easily replacable... :S
Aulularia grins at you.
Brother Aulularia shivers.
<span class="dwq_typed">'#m Apparently I keep alternating between wet and dry, too :p</span>
You say: Apparently I keep alternating between wet and dry, too :p
<span class="dwq_boldyellow"><u>Touchstone</u> tells you: They're all safe.</span>
<span class="dwq_typed">t Touchstone Great, thanks.</span>
You tell Touchstone: Great, thanks.
Touchstone points corpse.
Brother Aulularia woos.
<span class="dwq_typed">cheer</span>
You cheer enthusiastically.
<span class="dwq_boldyellow"><u>Touchstone</u> asks you: Leave it there for the moment, till things get sorted out, though?</span>
<span class="dwq_typed">t Touchstone Okay :)</span>
You tell Touchstone: Okay :)
Gillburt bows to Touchstone and you.
Touchstone sparkles brightly at Green Gillburt.
<span class="dwq_cyan">Touchstone exclaims to Green Gillburt: All yours!</span>
<span class="dwq_typed">bow Gillburt</span>
You bow to Green Gillburt.
Green Gillburt thanks Touchstone.
<span class="dwq_typed">grin</span>
You grin.
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: hi</span>
<span class="dwq_typed">t Gillburt Ello :)</span>
You tell Gillburt: Ello :)
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: just a moment....</span>
<span class="dwq_typed">nodnod Gillburt</span>
You nodnod at Green Gillburt.
Green Gillburt looks at you.
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: Right... let's take a look</span>
<span class="dwq_typed">l corpse</span>
This is the dead body of Mishal d'Ranged.
<span class="dwq_boldyellow">Wearing</span> : a pair of barbed wire underwear, a durable priest's shoulder pouch, a durable Sekkite shoulder pouch, two belt loops, an ivory penholder, a club
 badge, a dagger scabbard, a keyring necklace, a utility belt, a silver watch pin, Obsidian Bracelet, Brass Bracelet, Bronze Bracelet and Platinum Bracelet.
<span class="dwq_green">Carrying</span>: a flat cap, a set of morion prayer beads, a prayer book, a black backpack, a pair of black soft-soled boots, a blue crystal ring, a purple-black  leather overcoat, a silver moon dragon dagger and an orange cane.
Its purse is fit to burst!
<span class="dwq_typed">t Aulularia .. look at my corpse. Why is it *carrying* my overcoat, boots, backpack, cap and ring, all of which I was wearing? :S</span>
You tell Aulularia: .. look at my corpse. Why is it *carrying* my overcoat, boots, backpack, cap and ring, all of which I was wearing? :S
Aulularia smirks at you.
<span class="dwq_typed">rituals</span>
You know the following religious rituals:
blight              devout inquisition  food of life        minor shield        searing touch       visions
clarify             divine guard        haunting            paralysis           see alignment       warm
cool                divine hand         holy sacrifice      parch               see consecration    wicker ward
creeping doom       dust devil          holy weapon         profound darkness   silence             wrath
cure light wounds   far sight           horror              rage                sotto voce          
cure medium wounds  fear                light               raise dead          terror              
detect alignment    find                major shield        remember place      totem               
<span class="dwq_typed">t Aulularia Apparently I still have all of my rituals, too :P Dunno if that's normal or not ;)</span>
You tell Aulularia: Apparently I still have all of my rituals, too :P Dunno if that's normal or not ;)
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: It isn't :P</span>
<span class="dwq_typed">t Aulularia I know they normally disappear, but I haven't ever checked if that happens at the point of death or the point of res :P</span>
You tell Aulularia: I know they normally disappear, but I haven't ever checked if that happens at the point of death or the point of res :P
Aulularia grins at you.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: point of death.</span>
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: probably :P</span>
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: Could you explain what is the problem now. I understand you have your body back.</span>
<span class="dwq_typed">t Aulularia Probably. I'd test to see if I can perform one if there weren't two cre's standing by me :p</span>
You tell Aulularia: Probably. I'd test to see if I can perform one if there weren't two cre's standing by me :p
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: do it anyway :P</span>
<span class="dwq_typed">t Gillburt I'm not totally sure. I left my flat cap on while going AFK, and came back to find myself &quot;dead&quot; obviously, but I had no corpse, and apparently I wasn't appearing as a ghost to Aulularia. I can't check whether I appear as a ghost or not, but the corpse was definitely the main problem.</span>
You tell Gillburt: I'm not totally sure. I left my flat cap on while going AFK, and came back to find myself &quot;dead&quot; obviously, but I had no corpse, and apparently I wasn't appearing as a ghost to Aulularia. I can't check whether I appear as a ghost or not, but the corpse was definitely the main problem.
<span class="dwq_typed">t Gillburt Also I still have a list of rituals in &quot;rituals&quot;, which I always thought was supposed to disappear on death. It's possible they get removed on res, I guess, but I've never checked either way.</span>
You tell Gillburt: Also I still have a list of rituals in &quot;rituals&quot;, which I always thought was supposed to disappear on death. It's possible they get removed on res, I guess, but I've never checked either way.
<span class="dwq_typed">perform warm on me</span>
You need a holy symbol to perform this ritual.
<span class="dwq_typed">clw me</span>
You cannot perform cure light wounds because you are dead and you cannot grant the gift of life with a simple healing ritual.
<span class="dwq_cyan">Someone says: DO YOU EVER GET THAT FEELING OF DEJA VU?</span>
You turn and see Death standing behind you.
<span class="dwq_cyan">Death says: DIDN'T I HELP YOUR NAAN PASS ON LAST WEEK?</span>
<span class="dwq_cyan">Death says: THE GODS ALWAYS SEEM TO LET PEOPLE LIKE YOU HAVE ANOTHER CHANCE BUT I DON'T SEE THE POINT.</span>
<span class="dwq_typed">'#m Ooh.</span>
You say: Ooh.
The mist swirls and sparkles around Gillburt's body.
<span class="dwq_cyan">Death says: I SUPPOSE YOU WANT TO BE ALLOWED TO STAY, DO YOU?
<span class="dwq_typed">l</span></span>
[Tuna Walk commercial area]
<span class="dwq_cyan">&amp;</span>-<span class="dwq_cyan">*</span>-<span class="dwq_boldyellow">@</span>-<span class="dwq_cyan">*</span>-<span class="dwq_cyan">*</span>-
  |   |   
About halfway along Tuna Walk, this part of the docks looks south across the ocean and Bes Pelargic's harbour.  Tuna Walk runs east and west along the harbour and beyond.  The harbour is crammed with boats of all shapes and sizes and people milling around, pursuing their daily business, or at least someone's daily business, whichever is the most interesting.  To the east Tuna Walk goes through an ornate archway.
<span color="#808000">It is a very cold backspindlewinter's morning with a steady breeze, dense cloud cover and light sleet.
</span><span class="dwq_green">There are two obvious exits: <u>east</u> and <u>west</u>.</span>
A rickshaw driver is pulling the rickshaw along and Green Gillburt and Touchstone are standing here.
Two corpses of Mishal d'Ranged and a holy relic are on the ground, Binky is standing here, carrying Someone, Death is atop Binky here, an enamelled sign is on the building and a rickshaw is here being pulled by the rickshaw driver.
<span class="dwq_cyan">Death says: I REALLY DON'T LIKE DOING ALL THESE FAVOURS FOR YOU PEOPLE.</span>
<span class="dwq_cyan">Death says: I MEAN, WHAT'S IN IT FOR ME?</span>
<span class="dwq_typed">l corpses</span>
This is the dead body of Mishal d'Ranged.
This is the dead body of Mishal d'Ranged.
<span class="dwq_boldyellow">Wearing</span> : a pair of barbed wire underwear, a durable priest's shoulder pouch, a durable Sekkite shoulder pouch, two belt loops, an ivory penholder, a club
 badge, a dagger scabbard, a keyring necklace, a utility belt, a silver watch pin, Obsidian Bracelet, Brass Bracelet, Bronze Bracelet and Platinum Bracelet.
<span class="dwq_green">Carrying</span>: a flat cap, a set of morion prayer beads, a prayer book, a black backpack, a pair of black soft-soled boots, a blue crystal ring, a purple-black leather overcoat, a silver moon dragon dagger and an orange cane.
Its purse is fit to burst!
<span class="dwq_cyan">Death says: I'M KIND OF BUSY, HOW ABOUT ONE FREE EXTRA RIDE?</span>
<span class="dwq_cyan">Death says: YOU DIE A LOT.  PERHAPS I SHOULD JUST WAIT AROUND INSTEAD OF GOING ALL THE WAY HOME.</span>
<span class="dwq_typed">t Aulularia Heh. NOW I have Death talking to me... and there are two corpses of me on the ground ;)</span>
You tell Aulularia: Heh. NOW I have Death talking to me... and there are two corpses of me on the ground ;)
<span class="dwq_cyan">Death says: ENOUGH OF THAT.  I WONDER IF THE FISH ARE BITING...</span>
<span class="dwq_cyan">Death gets back onto Binky and rides away.</span>
You hear a pattering of many tiny feet.
<span class="dwq_boldyellow"><u>Aulularia</u> tells you: HA :P</span>
The ground suddenly opens up in front of your feet and a bunch of manically grinning dwarfs pop out and start bouncing around in front of you.
<span class="dwq_cyan">With a huge smile one of the grinning dwarfs whispers in your ear: Here, take this book - it'll tell you everything you need to know.  But don't mention it to Death.  Ok?</span>
Without waiting, they all leap back into the hole which slowly closes after them.
<span class="dwq_boldyellow"><u>Aulularia</u> asks you: two inventories?</span>
<span class="dwq_typed">t Aulularia Nah, one's empty :(</span>
You tell Aulularia: Nah, one's empty :(
<span class="dwq_typed">cheer</span>
You cheer enthusiastically.
<span class="dwq_typed">who pishe</span>
--------------------------------------------==========]  Discworld  [===========--------------------------------------------
Magistrate Jeanie the Archbishop of Pishe, Faithful, Lady of Light, Funeral Director
Brother Kloke the Verger of Pishe, Mapmaker Caretaker
Blessed Sister Sevelille the Deacon of Pishe, Happy to Help, Ray Of Sunshine
----------------------------There are three members of this group of people on the Discworld. &lt;---------------------------
<span class="dwq_typed">rituals</span>
You don't know any religious rituals.
<span class="dwq_typed">t Aulularia And yes, I really did still have my rituals. I tried performing a couple, but couldn't find one that didn't require a symbol/amulet/etc :(</span>
You tell Aulularia: And yes, I really did still have my rituals. I tried performing a couple, but couldn't find one that didn't require a symbol/amulet/etc :(
Aulularia grins at you.
<span class="dwq_typed">t Gillburt Right, shall I try finding a Pishite now, or is there still something up that you can see? :)</span>
You tell Gillburt: Right, shall I try finding a Pishite now, or is there still something up that you can see? :)
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: touchstone you appear to be OK now, in a dead way. At least you are a ghost now - but just a moment...
<span class="dwq_typed">t Sevelille Hey there. I, um, will probably need your help in a minute, if you're free :)</span></span>
You tell Sevelille: Hey there. I, um, will probably need your help in a minute, if you're free :)
<span class="dwq_boldyellow"><u>Sevelille</u> tells you: Of course.</span>
<span class="dwq_typed">t Gillburt Okay.</span>
You tell Gillburt: Okay.
<span class="dwq_typed">t Sevelille It was a rather buggy death, so I still have cre's trying to fix things, heh.</span>
You tell Sevelille: It was a rather buggy death, so I still have cre's trying to fix things, heh.
<span class="dwq_boldyellow"><u>Sevelille</u> tells you: Sure, let me know when you're ready.</span>
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: OK - you can go ahead and find a pishite</span>
<span class="dwq_typed">thank Gillburt</span>
You thank Green Gillburt.
<span class="dwq_typed">t Sevelille Right, I'm ready now :) At the ferry stop on Tuna Walk, BP.</span>
You tell Sevelille: Right, I'm ready now :) At the ferry stop on Tuna Walk, BP.
<span class="dwq_boldyellow"><u>Sevelille</u> tells you: On my way.</span>
<span class="dwq_typed">thank Sevelille</span>
You thank Sevelille.
Gillburt fetches Mort's sceptre from another dimension.
Blessed Sister Sevelille arrives from the west.
Sevelille smiles at you.
<span class="dwq_typed">bow sev</span>
You bow sev.
<span class="dwq_typed">bow Sevelille</span>
You bow to Blessed Sister Sevelille.
<span class="dwq_typed">:fails at tab-completion today.</span>
Blessed Sister Sevelille gets a set of polished malachite prayer beads from a pocket in a small shoulder pouch between opening and closing it.
Blessed Sister Sevelille holds a set of polished malachite prayer beads in her left hand.
You emote: The ghost of Mishal d'Ranged fails at tab-completion today.
Blessed Sister Sevelille gets a holy relic and a prayer book from a pocket in a hunter's pack.
Blessed Sister Sevelille gets a flat cap from a pocket in a utility belt.
Blessed Sister Sevelille removes an Offler-headed mask so she can wear a flat cap.
Blessed Sister Sevelille wears an Offler-headed mask.
Blessed Sister Sevelille kneels in prayer.
Blessed Sister Sevelille closes her eyes.
Blessed Sister Sevelille chants in a soft soothing voice.
Blessed Sister Sevelille softly speaks what sounds like a prayer.
Blessed Sister Sevelille chants in a soft sinister voice.
Blessed Sister Sevelille calls upon Pishe.
Blessed Sister Sevelille gestures at the open air.
Blessed Sister Sevelille looks expectant.
A soft light radiates from Blessed Sister Sevelille and slowly envelopes you.
You reappear in a more solid form.
You feel the attention of a higher being.
You feel strength returning to your body.
Your mind feels renewed.
You feel nimbleness returning to your body.
You feel health returning to your body.
You feel mentally attuned.
Knowledge of &quot;cool&quot; has been restored to you.
Knowledge of &quot;cure light wounds&quot; has been restored to you.
Knowledge of &quot;raise dead&quot; has been restored to you.
Knowledge of &quot;totem&quot; has been restored to you.
Knowledge of &quot;searing touch&quot; has been restored to you.
Knowledge of &quot;minor shield&quot; has been restored to you.
Knowledge of &quot;visions&quot; has been restored to you.
Knowledge of &quot;far sight&quot; has been restored to you.
Knowledge of &quot;silence&quot; has been restored to you.
Knowledge of &quot;detect alignment&quot; has been restored to you.
Knowledge of &quot;fear&quot; has been restored to you.
Knowledge of &quot;dust devil&quot; has been restored to you.
Knowledge of &quot;holy weapon&quot; has been restored to you.
Knowledge of &quot;cure medium wounds&quot; has been restored to you.
Knowledge of &quot;remember place&quot; has been restored to you.
Knowledge of &quot;light&quot; has been restored to you.
Knowledge of &quot;clarify&quot; has been restored to you.
Knowledge of &quot;devout inquisition&quot; has been restored to you.
Knowledge of &quot;warm&quot; has been restored to you.
Knowledge of &quot;parch&quot; has been restored to you.
Knowledge of &quot;find&quot; has been restored to you.
Knowledge of &quot;haunting&quot; has been restored to you.
The dark brown book crumbles and vanishes mysteriously.
Blessed Sister Sevelille removes the Offler-headed mask so she can remove the flat cap.
Blessed Sister Sevelille wears the Offler-headed mask.
Blessed Sister Sevelille puts the flat cap in a pocket in the utility belt.
Blessed Sister Sevelille kneels down.
Blessed Sister Sevelille closes her eyes.
<span class="dwq_typed">cheer</span>
You cheer enthusiastically.
Blessed Sister Sevelille utters a lengthy prayer.
Blessed Sister Sevelille places her hands on you.
<span class="dwq_green">Hp: 1796 (1796) Gp: 422 (422) Xp: 137568</span>
<span class="dwq_typed">thank Sevelille muchly</span>
You thank Blessed Sister Sevelille muchly.
Blessed Sister Sevelille appears to be checking out all your wounds.
<span class="dwq_typed">'#m Ah, much better.</span>
You say: Ah, much better.
<span class="dwq_typed">smile</span>
You smile.
<span class="dwq_typed">score</span>
You have 1796 (1796) hit points, 422 (422) guild points, 259 (640) quest points and 65 (71) social points.
Your current experience is 137664 and you are level 308 in the priesthood of Sek; your overall rating is 38439.
You have died 6 times and can die 5 times before you are completely dead.
Your wimpy is set to 30%.
You are unburdened (34%) and quite comfortable.
You are extremely evil, worshipping Seven-Handed Sek.
You are 124 days, 19 hours, 33 minutes and 53 seconds old and have logged in 719 times.
<span class="dwq_boldyellow"><u>Gillburt</u> tells you: Given you lost two lives when you should only have lost the one, I'll give you a life back.</span>
Touchstone beams at you.
<span class="dwq_typed">t Gillburt I was just about to mention that. Thanks :)</span>
You tell Gillburt: I was just about to mention that. Thanks :)
Gillburt pushes a button on Mort's scepter, and a warm glow envelopes you.
<span class="dwq_typed">score</span>
You have 1796 (1796) hit points, 422 (422) guild points, 259 (640) quest points and 72 (72) social points.
Your current experience is 137703 and you are level 308 in the priesthood of Sek; your overall rating is 38439.
You have died 6 times and can die 6 times before you are completely dead.
Your wimpy is set to 30%.
You are unburdened (34%) and quite comfortable.
You are extremely evil, worshipping Seven-Handed Sek.
You are 124 days, 19 hours, 34 minutes and 18 seconds old and have logged in 719 times.
The eggshell blue moon dragon snuffles Blessed Sister Sevelille's cheek.
<span class="dwq_cyan">Blessed Sister Sevelille asks with a Sto Plains accent: Glad to help, need anything else?</span>
<span class="dwq_typed">slip 1 royal to Sevelille</span>
You slip one Ankh-Morpork royal to Blessed Sister Sevelille.
<span class="dwq_cyan">The rickshaw driver says in Agatean with a Bes Pelargic accent: I can take you anywhere you need to go, well for a given value of anywhere.</span>
Sevelille thanks you.
<span class="dwq_typed">'#m That will be all, thank you.</span>
You say: That will be all, thank you.
<span class="dwq_typed">grin</span>
You grin.
<span class="dwq_typed">thank Gillburt muchly</span>
You thank Green Gillburt muchly.
Blessed Sister Sevelille nods.
Blessed Sister Sevelille leaves west.
<span class="dwq_typed">wave Sevelille</span>
You wave to Sevelille.
Gillburt bows to you.
<span class="dwq_typed">smile Gillburt</span>
You smile at Green Gillburt.
Touchstone waves.
Touchstone moves through a mysterious oak door that wasn't there a moment ago, and isn't there a moment later.
<span class="dwq_typed">thank Gillburt,Touchstone</span>
You thank Touchstone and Gillburt.
<span class="dwq_typed">wave Gillburt,Touchstone</span>
You wave to Touchstone and Gillburt.
Gillburt waves to you.
The wailing, breathless melody on the bagpipes fades away as Green Gillburt disappears from view.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<?php echo $this->partial("last-mod-time.phtml", array("filename"=>__FILE__)) ?>
