<article>
<p class="dwquote"><a id="log1" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
It seems easier to perform holy sacrifice because you are near holy ground.
You raise your arms towards the heavens, dagger in hand.

<span class="dwq_discon">&lt;&lt;Session Disconnected: 9:40 pm&gt;&gt;</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Starting to perform Holy Sacrifice immediately before being disconnected. Luckily this was a crash and not a simple disconnection, or I may have been logging back on to see Death.</p>
</article>

<article>
<p class="dwquote"><a id="log2" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
You enter the flame, feeling perfectly at one with Sek for a moment before you suddenly find yourself elsewhere.
The centre of the Royal Market <span class="dwq_green">[n,s,e,w]</span>.
A hairy bum and a pie seller are standing here.
A wooden pole with a bright blue note and a silver note attached to it is standing on the side of the road, three pumpkins and a medium sized mauve bottle are on the ground and a lamp post is here, lighting up the street.
For a moment you feel like skipping, but it passes.
You remove the flat cap.
The suspicious character moves slowly out of the shadows.
You carefully attach the diamond Berilia charm to the gold charm bracelet.
The suspicious character sidles up to you ingratiatingly.
<span class="dwq_cyan">The suspicious character asks you with a Sto Plains accent: Evening mister. Fancy a good time?</span>
The suspicious character peers at you, grinning disarmingly.
The suspicious character grins darkly.
The suspicious character attacks you from behind.  You recall him standing right in front of you just a second ago.
You are shocked and confused.
Moving swiftly, the suspicious character slices your right leg with his meat cleaver.
With surprising speed, the suspicious character hacks your chest with his cheap and nasty switchblade.
Catching you by surprise, the suspicious character slices your left foot with his cheap and nasty switchblade.
<span class="dwq_boldyellow">Hp: 742 (1503) Gp: 79 (325) Xp: 11291</span>
The suspicious character slices your right arm with his meat cleaver.
<span class="dwq_boldyellow">Hp: 588 (1428) Gp: 79 (315) Xp: 11294</span>
The suspicious character shoves you sending you crashing to the ground.
<span class="dwq_boldyellow">Hp: 591 (1428) Gp: 82 (315) Xp: 11297</span>
The suspicious character cuts your chest with his meat cleaver.
The suspicious character cuts your left arm with his cheap and nasty switchblade.
<span class="dwq_boldyellow">Hp: 404 (1428) Gp: 85 (315) Xp: 11300</span>
The suspicious character cuts your back with his meat cleaver.
<span class="dwq_boldred">Hp: 317 (1428) Gp: 88 (315) Xp: 11303</span>
You stand up.
<span class="dwq_boldred">Hp: 320 (1428) Gp: 91 (315) Xp: 11306</span>
The suspicious character launches a powerful attack.  The suspicious character hacks your chest with his meat cleaver.
You no longer feel shocked and confused.
The suspicious character gets 11 Djelian talents, 10 Lancre shillings, 6 Ankh-Morpork pence, one Ankh-Morpork royal, some Ankh-Morpork dollars, 9 Lancre crowns, one Lancre farthing, 8 Ankh-Morpork ten-dollars, 5 Agatean Empire rhinu, 2 Ankh-Morpork ten-pences, 5 Genuan livres and some Genuan cents from the corpse of Mishal d'Ranged.
Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?  SHALL WE POPPADOM TO THE NEXT DIMENSION?
You turn and see Death standing behind you.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Passaging into Sto Lat before being positively wrecked by some random NPC. Mishal's first death, too. I especially like the way that after killing me the NPC proceeded to steal three royals' worth of stuff from my corpse (which included my watch).</p>
</article>

<article>
<p class="dwquote"><a id="log3" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
You are having trouble performing resurrect because you are using the white cane as an external focus for the ritual.  However, this is mitigated by the fact that you are near holy ground.
You kneel in prayer.
You close your eyes, and contemplate higher things.
You chant the ritual for body preservation.
You recite the prayer for body regeneration.
You chant the ritual for summoning the image of Death.
You call upon Sek to protect you from Death's aura.
You communicate your needs to Death.
Death ponders the situation.
Death tells you: HMM... HE DOESN'T SEEM TO BE A REGULAR CLIENT OF MINE.  I SUPPOSE THAT I CAN TURN A BLIND EYE.
Death's image vanishes.
Illuminate starts to glow softly.
Illuminate appears in more solid form.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Mishal's first resurrect. Resurrect rods are the best.</p>
</article>

<article>
<p class="dwquote"><a id="log4" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?
You turn and see Death standing behind you.
Death says: I SUPPOSE YOU WANT TO BE ALLOWED TO STAY, DO YOU?
Death says: OH, BUGGER, THERE'S A TYPO IN THE DEATH LOG.
Death gets a sandtimer from within the dark cloak and looks at it.
Death says: MIND YOU, IT WON'T BE LONG.  I'LL SEE YOU LATER.
Death disappears in a puff of nothing.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">A random room chat in Bes Pelargic's Red Triangle District.</p>
</article>

<article>
<p class="dwquote"><a id="log5" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
The Tuna Walk commercial area <span class="dwq_green">[e,w]</span>.
A starving urchin is standing here and a rickshaw driver is pulling the rickshaw along.
An enamelled sign is on the building and a rickshaw is here being pulled by the rickshaw driver.
Greasy sparks crawl over the north wall, and a door silently materialises.
<span class="dwq_cyan">The starving urchin asks in Agatean: You know Rincewind?</span>
<span class="dwq_cyan">The starving urchin sidles up to you, suddenly limping.</span>
<span class="dwq_cyan">The starving urchin exclaims in Agatean: Gimme some Pununiya, Tonogono</span>
<span class="dwq_cyan">The starving urchin asks in Agatean: Ryoya, you fat! Doryu Jimpaiya Kinosoko Doryu forn Nigari-ka</span>
<span class="dwq_cyan">The starving urchin scratches busily.</span>
<span class="dwq_cyan">The starving urchin sticks his finger up his nose and digs in.</span>
<span class="dwq_typed">con urchin</span>
<span class="dwq_red">The starving urchin looks pretty nasty.</span>
&gt; <span class="dwq_typed">fear urchin</span>
It seems easier to perform fear because you have recently prayed and you are near holy ground.
&gt; You utter a short prayer.
You call upon Sek to fill a starving urchin with fear.
The starving urchin looks worried.
The starving urchin opens the shop door.
The starving urchin leaves north.
The starving urchin closes the shop door.
The door in the north wall flickers, and vanishes.  A few lazy worms of fire remain on the wall in its place, but they quickly wink out.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">That solved <i>that</i> problem... I feel sorry for the poor natives of the Brown Islands, though.</p>
</article>

<article>
<p class="dwquote"><a id="log6" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
LPmud version : FluffOS v1.36 on port 4242.
Welcome to Discworld: the stuff of which dreams are made.

Silently, slowly and surely, Great A'Tuin paddles through space, its
great eyes surveying the dark, empty wastes before and behind it.
Standing on A'Tuin's great back are four enormous elephants, straining
under the colossal weight of the Discworld itself.  It sparkles with
magic, reflects the light of the stars and generally fails to be as
unobtrusive as possible.

Q - Quit
M - Print this menu again
D - Delete your character
R - Request a temporary password
U - Short list of who is on-line
P - Uptime
F - Finger someone
N - New character
G - Guest character

Or, enter your current character's name

Your choice: <span class="dwq_system">mishal</span>
<span class="dwq_system">PASSWORD</span>

                                   Discworld
                     Where all your dreams can't come true.

                                   Auditors                                    

                            Taffyd   Sojan   Dasquian
                                Wodan   Turrican   

                          Avatars of the Apocralypse
                               Pinkfish   Ceres
                                   
                                    

Please imagine a very nice picture of four Elephants standing on the back of
a Turtle (sex unknown) swimming through space.  On the Elephants rests the
Disc of the world, garlanded by the long waterfall at its vast circumference
and domed by the baby blue vault of heaven.  Imagine this, because there is
not enough room here to draw it.

Enter password: 
You last logged in from <i>[snip]</i> (<i>[snip]</i>) and are currently logged in from <i>[snip]</i> (<i>[snip]</i>).

     **************************************************************
     * It is your responsibility to know and adhere to the rules. *
     * If you are not sure what they are read 'help rules'.       *
     * Ignorance of the rules will not be accepted as a defence.  *
     **************************************************************

Queued command: qwho
Queued command: score brief
[Mishal enters Discworld -- Taxi]
Queued command: glance
The aged zombie mumbles something about brainssss under its breath.
The aged zombie moves aggressively towards you!
The aged zombie jabs you in the chest.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Auto-attacked on login. Thankfully it was a fairly weak NPC ("The aged zombie looks pretty nasty.") and I had full GP, otherwise that could have ended quite differently.</p>
</article>

<article>
<p class="dwquote"><a id="log7" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
<span class="dwq_boldgreen">(Priests) Spank wisps that he blinks.</span>
<span class="dwq_boldgreen">(Priests) Spank wisps: Striking TM.</span>
<span class="dwq_boldgreen">(Priests) Thakh wisps that he mourns.</span>
<span class="dwq_boldgreen">(Priests) Thakh wisps: That was an expensive TM..</span>
<span class="dwq_typed">sb</span>
Hp: 1503(1503)  Gp: 286(347)  Xp: 96563
&gt; <span class="dwq_typed">wd</span>
---------------------------==========]  Discworld  [===========---------------------------
Brother Spank a'Thon the Votary of Sek, Cherry Flavoured, Public Benefactor
-------------&gt; There is one member of this group of people on the Discworld. &lt;------------
&gt; <span class="dwq_typed">ls spank</span>
You hold a ribboned baton in your right hand.
You get a ribboned baton from a pocket in the black backpack.
You are having trouble performing longsight because you are using the ribboned baton as an external focus for the ritual and you are far from holy ground.
Queued command: put longsight in backpack
&gt; You utter a quick prayer.
You cover your eyes.
You briefly see a vision.

     This is the approximate centre of the "Divine Flower" marketplace.  Shoving their way
     through the crowd, hundreds of people are here, bartering, buying, and selling
     whatever strikes their fancy.  Among the multitude of stalls that are crammed in
     here, there is one that seems to be selling lanterns.  The marketplace extends in all
     directions except to the west, where Hook Street begins.
     <span class="dwq_yellow">It is a slightly chilly secundus autumn's evening with almost no wind and medium
     cloud cover.</span>
     <span class="dwq_green">There are eight obvious exits: south, east, southeast, northwest, north, northeast,
     west and enter stall.</span>
     The ghost of Spank a'Thon and a chivalrous McSweeney samurai are standing here.
     The corpse of Spank a'Thon is on the ground.

You put the ribboned baton in a pocket in the black backpack.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<?php /* <p class="dwcaption"></p> */ ?>
</article>

<article>
<p class="dwquote"><a id="log8" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
<span class="dwq_boldcyan">(Apex) Acantha wisps: Dariana, have you tried playing Gufnork's organ?"
(Apex) Thakh wisps that he leers.
(Apex) Syaoran wisps: nope, thats aaaalllll you acantha :)
(Apex) fewyn wisps: that sounds very very very dirty...
(Apex) Acantha wisps: Syaoran, i'm surprised. You're running for HP and you've never touched Gufnork's organ? I play with it daily.
(Apex) Julnar wisps: yeah, how will gufnork know you're serious if you don't touch his organ?
(Apex) Syaoran wisps: I use Gufnorks Flute
(Apex) Acantha wisps: Exactly. Mind you, most days I make sure I'm carrying a towel to wipe my face, or that I have time to visit the baths very quickly afterwards.
(Apex) Julnar wisps: and how well do you play with his instrument?
(Apex) Syaoran wisps: every time I pray. just before I pray
(Apex) Syaoran wisps: With obvious musical skill, you play a complex yet harmonious melody on your bamboo flute.
(Apex) Thakh wisps: What does bamboo have to do with Gufnork?
(Apex) Acantha wisps: That's a bamboo flute. Only Naefela and I play His Organ. Poor Gufnork.
(Apex) Syaoran wisps: it's name is gufnorks flute, it just doesnt know it yet.
(Apex) Thakh wisps: Both at once?
(Apex) Hypo wisps: Personally, if I was Gufnork, I wouldn't want Syaoran anywhere near my organ.
(Apex) Thakh wisps that he agrees with Hypo.
(Apex) Julnar wisps: gufnore wants more people to play with his organ
(Apex) Syaoran wisps: tahts cause your a heathen.
(Apex) Syaoran wisps that he points at Hypo
(Apex) Thakh wisps: I'd prefer Acantha and Nafaela playing my organ over Syaoran too, though, he has a point.
(Apex) Julnar wisps: well I have more skills with percussion insturments but I don't mind trying my hand at an organ
(Apex) Acantha wisps: Go try, Julnar.
(Apex) Acantha wisps: Naefela and I played a duet once or twice.
(Apex) Thakh wisps: I'm sure Acantha could teach you lots.</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<? /* <p class="dwcaption"></p> */ ?>
</article>

<article>
<p class="dwquote"><a id="log9" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
&gt; <span class="dwq_typed">bp</span>
Now using Agatean for speaking and writing.
You remove a gold cobra charm from Obsidian Bracelet.
You feel a momentary itch at the back of your neck.
You wear a flat cap.
Queued command: perform divine hand on gold cobra charm
Queued command: enter flame
Queued command: remove flat cap
Queued command: add gold cobra charm to obsidian bracelet
&gt; It seems easier to perform divine hand because you are near holy ground.
You say a prayer over a gold cobra charm.
For a moment you feel like skipping, but it passes.
You notice a roguish thief nearby.
<span class="dwq_cyan">The roguish thief exclaims: Cor! Even better than a plate full of cabbage!</span>
Bright white and red flashes surround the roguish thief as he triggers a religious ward!
The roguish thief is paralysed.
You attempt to visualise the place that you remembered.
You pray to Sek to grant you the means to travel there.
You meditate on the holiness of Sek before vanishing.
Sek's chamber <span class="dwq_green">[none]</span>.
You enter the flame, feeling perfectly at one with Sek for a moment before you suddenly find yourself elsewhere.
The Tuna Walk commercial area <span class="dwq_green">[e,w,n]</span>.
A manky rat and a rickshaw driver are standing here.
A rickshaw is here being pulled by the rickshaw driver and an enamelled sign is on the building.
Cannot find "flat cap", no match.
You carefully attach the gold cobra charm to Obsidian Bracelet.
You hear a faint voice in your head: Mishal!  It's the flat cap.  I'm currently being carried by a roguish thief in near the north end of Short Street.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Yay for wards - paralysis and sotto voce, in this case. I paid A$100 to the person who killed the thief and found my cap, which is somewhat cheaper than spending two to five times that much for a new one. Everyone's a winner.</p>
</article>

<article>
<p class="dwquote"><a id="log10" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
&gt; <span class="dwq_typed">find elera</span>
It seems easier to perform find because you are near holy ground.
&gt; You utter a quick prayer.
You hold up your set of prayer beads.
You begin to get the feeling that something is wrong.
The world goes black! You are blind.
<span class="dwq_typed">l</span>
Queued command: l
&gt; You are blind and cannot see.
Elera eyes you over.
<span class="dwq_typed">priests Awesome!</span>
You whisper into the silver watch pin.
<span class="dwq_boldgreen">(Priests) Mishal wisps: Awesome!</span>
&gt; <span class="dwq_typed">sob elera</span>
You sob on someone's shoulder.
&gt; Your vision has returned.
<span class="dwq_boldyellow">Elera tells you: hah hah, you're blind :P</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Performing find on creators is Very Bad, apparently :(</p>
</article>

<article>
<p class="dwquote"><a id="log11" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
A road <span class="dwq_green">[n,w,e]</span>.
An old villager is standing here.
A small wooden numberplate is on the north wall and a wooden pole with an olive note and a white note attached to it is here.
<span class="dwq_typed">sb</span>
Hp: 1503(1503)  Gp: 183(349)  Xp: 1578285
&gt; <span class="dwq_typed">s</span>

AAARRRGGGHHH!!!

An air room <span class="dwq_green">[none]</span>.
&gt; <span class="dwq_typed">tbr</span>
You can't concentrate enough to twist the blue crystal ring.
&gt; <span class="dwq_boldred">You find it hard to float and make a quick trip thirty-five yards downwards.</span>
Some moorland close to a mountain range and an evergreen forest <span class="dwq_green">[n,climb e,climb s]</span>.
<span class="dwq_boldred">Ouch, that hurt (1786).</span>
<span class="dwq_cyan">Someone says: MY, WE'VE BEEN A BIT CARELESS, HAVEN'T WE?  SHALL WE POPPADOM TO THE NEXT DIMENSION?</span>
You turn and see Death standing behind you.
<span class="dwq_cyan">Death says: PERHAPS YOU SHOULD TAKE A NUMBER,  WE ARE BUSY TODAY.</span>
<span class="dwq_cyan">Death says: THE GODS ALWAYS SEEM TO LET PEOPLE LIKE YOU HAVE ANOTHER CHANCE BUT I DON'T SEE THE POINT.</span>
<span class="dwq_cyan">Death says: I SUPPOSE YOU WANT TO BE ALLOWED TO STAY, DO YOU?</span>
<span class="dwq_cyan">Death says: I REALLY DON'T LIKE DOING ALL THESE FAVOURS FOR YOU PEOPLE.</span>
<span class="dwq_cyan">Death says: I MEAN, WHAT'S IN IT FOR ME?</span>
<span class="dwq_cyan">Death says: OH DEAR, IT SEEMS SEK WON'T SEE YOU RIGHT NOW.</span>
<span class="dwq_cyan">Death says: JUST DON'T TELL ANYONE I DID THIS FOR YOU!</span>
<span class="dwq_cyan">Death says: I MAY NOT BE SO FORGIVING IN THE FUTURE.  BE MORE CAREFUL.</span>
<span class="dwq_cyan">Death gets back onto Binky and rides away.</span>
You hear a pattering of many tiny feet.
The ground suddenly opens up in front of your feet and a bunch of manically grinning dwarfs pop out and start
bouncing around in front of you.
<span class="dwq_cyan">With a huge smile one of the grinning dwarfs whispers in your ear: Here, take this book - it'll tell you everything you need to know.  But don't mention it to Death.  Ok?</span>
Without waiting, they all leap back into the hole which slowly closes after them.

<i>(Later)</i>

The Hall of Heroes <span class="dwq_green">[d]</span>.
A swarm of fireflies is buzzing around and a rough tom cat, an aquamarine moon dragon, Sultana Keb Casaubon, Kefka Nightingale and Lanfear are standing here.
<span class="dwq_typed">teach me 44 ot.he from lanfear</span>
Lanfear offers to teach you 44 levels of other.health for 1017217 xp.
Use "learn" to learn the skill.
&gt; <span class="dwq_typed">learn ot.he from lanfear</span>
Lanfear starts to teach you 44 levels of other.health for 1017217 xp.
Saving...
Saving...
You finish learning 44 levels of other.health from Lanfear.
<span class="dwq_typed">thank lanfear muchly</span>
You thank Lanfear muchly.
&gt; <span class="dwq_typed">sb</span>
Hp: 1695(1695)  Gp: 349(349)  Xp: 16738
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Falling off the Ramtops.</p>
</article>

<article>
<p class="dwquote"><a id="log12" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
<span class="dwq_boldred">Offler the Crocodile God shouts: Game ith webooting in 7 minuteth.</span>
<span class="dwq_boldblue">(Two) Sokkard wisps: Hmmm, Offler-goodness.
(Two) Sokkard wisps: Right! Now what shall I sing? Something from Mellow Yellow Wahooni Fruits, The Hamlet Persons, Newbie King, Lappet Faced Worriers, Enim Rac, Patricienne, Areyem, Mc Mallet, Lynched Liam or Orphans Impovision Workshop?
(Two) Pit wisps: lynched liam
(Two) Sokkard wisps: Rightio, Pit, Lynched Liam it is then!
(Two) Sokkard wisps: ... Whatever!
(Two) Sokkard wisps: I went down to Morpork and saw Dibbler
(Two) Sokkard wisps: He was, like, Sausage, Guv?
(Two) Sokkard wisps: And I was, like, Whatever!
(Two) Sokkard wisps: Then this troll comes up to me and she's all, like,
(Two) Sokkard wisps: Hey, aren't you that Sokkard??
(Two) Sokkard wisps: And I'm, like, Yeah, whatever!
(Two) Sokkard wisps: So later I'm at the Mended Drum
(Two) Sokkard wisps: And this witch comes up
(Two) Sokkard wisps: And she's, like, Wotcher!
(Two) Sokkard wisps: And I'm, like, Yeah, whatever!
(Two) Sokkard wisps: 'Cuz this is my
(Two) Sokkard wisps: Ankh-Mor-pork of Whatever!
(Two) Sokkard wisps: And this is my
(Two) Sokkard wisps: Ankh-Mor-pork of Whatever!
(Two) Sokkard wisps: And this is my
(Two) Sokkard wisps: Ankh-Mor-pork of Whatever!
(Two) Sokkard wisps: And then it's three A.M.
(Two) Sokkard wisps: And I'm in the Shades, wearing my leather
(Two) Sokkard wisps: This 'sasswot comes up and he's, like, Hey, punk!
(Two) Sokkard wisps: I'm, like, Yeah, whatever!
(Two) Sokkard wisps: Then I'm spamming, on (two)
(Two) Sokkard wisps: Captain Carrot comes up and is, like,
(Two) Sokkard wisps: 'Hey, I thought I told you...'
(Two) Sokkard wisps: And I'm, like, Yeah, whatever!
(Two) Sokkard wisps: And then up comes Ilik
(Two) Sokkard wisps: I'm, like, Yo, Ilik. What's up?
(Two) Sokkard wisps: He's, like, Nothin'
(Two) Sokkard wisps: And I'm, like, That's cool.
(Two) Sokkard wisps: 'Cuz this is my,
(Two) Sokkard wisps: Ankh-Mor-pork of Whatever!
(Two) Sokkard wisps: And this is my,
(Two) Sokkard wisps: Ankh-Mor-pork of Whatever!</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Spammiest NPC on the Disc! (Most unfortunatey I know the original song that Sokkard is parodying)</p>
</article>

<article>
<p class="dwquote"><a id="log13" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
Aemi has died for the last time.  But the Smiling Chimera, sw corner of the marketplace in OC, also stocks some very shiny priestly items.
<span class="dwq_red">(One) Fayte wisps: wow.. way to go to an effort for advertising
(One) positrix wisps: I was wondering if I'd imagined that...
(One) Gwydion wisps: All praise the People's Endeavour! :D</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<article>
<p class="dwquote"><a id="log14" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
Blessed Mother Cailleach visits you unexpectedly!
Blessed Mother Cailleach looks at you.
Cailleach grins at Nella and you.
<span class="dwq_typed">scream cailleach</span>
You scream loudly at Blessed Mother Cailleach.
> Blessed Mother Cailleach gives a red silk bra to you.
Cailleach fondles you gently.
<span class="dwq_typed">:feels unexpectedly visited.</span>
You emote: Mishal d'Ranged feels unexpectedly visited.
> Blessed Mother Cailleach cackles happily.
<span class="dwq_typed">sob</span>
You sob quietly.
> Blessed Mother Cailleach looks at you.
<span class="dwq_typed">l bra</span>
This is a simple yet elegant red bra made of fine silk.
It is in excellent condition.
> <span class="dwq_typed">wear bra</span>
You remove a black backpack and a long dark cloak so you can wear a red silk bra.
You wear a black backpack and a long dark cloak.
> <span class="dwq_typed">spock</span>
You raise one eyebrow.
> <span class="dwq_typed">remove bra</span>
You remove the long dark cloak and the black backpack so you can remove the red silk bra.
You wear the long dark cloak and the black backpack.
> Blessed Mother Cailleach approves
<span class="dwq_cyan">Blessed Mother Cailleach says with a Lancrastian accent: enjoy the cleavage dear</span>
Cailleach waves lazily to you.
<span class="dwq_typed">'#m Oh I will do.</span>
You say: Oh I will do.
> Blessed Mother Cailleach raises her hands in the air and cries out.
Blessed Mother Cailleach traces out a symbol in the air with her holy symbol.
Blessed Mother Cailleach steps forward and seems to vanish, leaving behind a lingering sound of champagne corks popping.
Blessed Mother Cailleach visits you unexpectedly!
Blessed Mother Cailleach rolls around on the floor laughing.
<span class="dwq_typed">'#m ....</span>
You say: ....
> <span class="dwq_cyan">Blessed Mother Cailleach says with a Lancrastian accent: Boo</span>
Cailleach pets you like a moose stuck in a tree.
<span class="dwq_typed">:feels unexpectedly visited. Again.</span>
You emote: Mishal d'Ranged feels unexpectedly visited. Again.
> Cailleach moshes up against you drunkenly.
<span class="dwq_cyan">Blessed Mother Cailleach says with a Lancrastian accent: looks that way</span>
Blessed Mother Cailleach looks at you.
<span class="dwq_typed">comfort cailleach</span>
You comfort Blessed Mother Cailleach.
> Blessed Mother Cailleach giggles.
Cailleach waves to Nella and you.
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Visit is such a bizarre ritual. And totally not random, apparently.</p>
</article>

<article>
<p class="dwquote"><a id="log15" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
 <span class="dwq_red">#</span><span class="dwq_green">e</span><span class="dwq_cyan">~</span>         The land is lit up by the eerie light of the waxing crescent moon.
 <span class="dwq_green">e</span><span class="dwq_red">#</span><span class="dwq_green">e</span>         This is a sizable suspension bridge spanning high over Lancre Gorge, serving
  <span class="dwq_green">e</span><span class="dwq_red">#</span><span class="dwq_cyan">~</span> <span class="dwq_green">f  f</span>  as the gateway into the kingdom of Lancre.  Stone towers stand at either end
   <span class="dwq_green">e</span><span class="dwq_red">#</span><span class="dwq_cyan">~</span><span class="dwq_green">f</span><span class="dwq_red">#</span><span class="dwq_green">f</span>   of the bridge, supporting thick chains that actually hold up the wooden
    <span class="dwq_green">e</span><span class="dwq_boldyellow">@</span><span class="dwq_red">#</span><span class="dwq_green">f</span>    road surface.  Stands of tall evergreen trees cover the ground to the west
   <span class="dwq_green">ee</span><span class="dwq_cyan">~</span><span class="dwq_green">ff</span>    and southwest, some falls are roaring loudly to the south, stands of tall
    G<span class="dwq_cyan">~</span>G     trees cover the ground to the northeast and southeast and a gently-flowing
    G <span class="dwq_cyan">~</span>     river is to the north.  Ten miles to the southeast is Lancre Town and five
   <span class="dwq_green">ee</span> GG    miles to the east is the village of Mad Stoat.
            <span class="dwq_yellow">It is a damn cold backspindlewinter's night with a strong breeze and some
            puffy clouds.</span>
            <span class="dwq_green">There are three obvious exits: northwest, east and down.</span>
            A customs troll is standing here.
> <span class="dwq_cyan">The customs troll says with a Lancrastian accent: Hullo, 'dis is a customs inspection.</span>
<span class="dwq_cyan">The customs troll asks with a Lancrastian accent: Do you have any beer, spirits, wines, liquors, hallucinogenic herbage or books of a lewd or licentious nature?</span>
<span class="dwq_typed">'#m No.</span>
Queued command: '#m No.
> You say: No.
<span class="dwq_cyan">The customs troll asks with a Lancrastian accent: Sure?</span>
<span class="dwq_typed">'#m Yes.</span>
You say: Yes.
> <span class="dwq_cyan">The customs troll asks with a Lancrastian accent: Would you like some?</span>
<span class="dwq_typed">'#m Yes, please.</span>
You say: Yes, please.
> <span class="dwq_cyan">The customs troll says with a Lancrastian accent: Right, 'ere's what I have. Feel free to list, buy or browse.</span>
<span class="dwq_typed">list goods of troll</span>
> <span class="dwq_cyan">The customs troll says to you with a Lancrastian accent: I have the following items for sale:</span>
<span class="dwq_cyan">The customs troll says to you with a Lancrastian accent: I have a copy of "Craggy and Beautiful" for Ls 5|6 3/4.</span>
<span class="dwq_cyan">The customs troll says to you with a Lancrastian accent: I have nine medium sized green bottles for Ls 3|5 3/4 each.</span>
<span class="dwq_cyan">The customs troll says to you with a Lancrastian accent: I have eight medium sized black bottles for LC 2|10|8 3/4 each.</span>
<span class="dwq_cyan">The customs troll says to you with a Lancrastian accent: I have six medium sized brown bottles for LC 1|1|10 3/4 each.</span>
<span class="dwq_cyan">The customs troll says to you with a Lancrastian accent: I have five badly-rolled cigarettes for Ls 4|2 each.</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<article>
<p class="dwquote"><a id="log16" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
> <span class="dwq_typed">quit</span>
A small gecko takes your hand and rushes you to the departure lounge.
> [Mishal leaves Discworld -- Taxi]
This is Greco's day off.
Gumboot, Greco's distant relative, is here to take your information.  Gumboot looks very confused and sticks the
pencil in her ear.
Gumboot smiles strangely.
<span class="dwq_cyan">Gumboot says: Well. Uhhhh. That's it.</span>
<span class="dwq_cyan">Gumboot says: I... Umm. Hope.</span>
You clamber about a giant spider.  Gumboot starts to walk out the door and stands on one of its feet.  You are
flung from the back of the giant spider out through the door and float meaninglessly through space.  You hope you
will be seen again...
Do come again!
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
</article>

<article>
<p class="dwquote"><a id="log17" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
<span style="color:#C0C0C0;">     </span><span style="color:#008080;">*</span><span style="color:#C0C0C0;">      This is the centre of the market square in Ohulan-Cutash.  There is quite a throng of townspeople here,
   | | </span><span style="color:#800000;">+</span><span style="color:#C0C0C0;">    all trying to get to the stalls to buy various products that are on offer.  The town well attracts all
   </span><span style="color:#008080;">&amp;</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">*</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">*</span><span style="color:#800000;">+</span><span style="color:#C0C0C0;">   sorts of people, from wealthy merchants to humble farmwives.  The market sprawls out in all directions.
</span><span style="color:#800000;"> +</span><span style="color:#C0C0C0;"> |x|x|    </span><span style="color:#808000;">It is a very warm summer prime's afternoon with almost no wind and a beautifully clear sky.
</span><span style="color:#C0C0C0;"> </span><span style="color:#008080;"> *</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">&amp;</span><span style="color:#C0C0C0;">-</span><span style="color:#FFFF00;">@</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">*</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">@</span><span style="color:#C0C0C0;">- </span><span style="color:#008000;">There are eight obvious exits: north, south, east, west, northeast, southeast, southwest and northwest.
</span><span style="color:#C0C0C0;">   |x|x| |  A bright red swamp dragon is lying here and a sad peasant, two grumbling peasants, a crimson moon
  </span><span style="color:#800000;">+</span><span style="color:#008080;">*</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">*</span><span style="color:#C0C0C0;">-</span><span style="color:#008080;">*</span><span style="color:#C0C0C0;">-   dragon, Goody Mellisandre and Sica DeLaCroix are standing here.
   | | |    A </span><span style="color:#800000;">C</span><span style="color:#C0C0C0;">h</span><span style="color:#800000;">r</span><span style="color:#C0C0C0;">i</span><span style="color:#800000;">s</span><span style="color:#C0C0C0;">t</span><span style="color:#800000;">m</span><span style="color:#C0C0C0;">a</span><span style="color:#800000;">s</span><span style="color:#C0C0C0;"> T</span><span style="color:#800000;">r</span><span style="color:#C0C0C0;">e</span><span style="color:#800000;">e</span><span style="color:#C0C0C0;"> is standing next to the well and a wooden pole with a green note attached to it is
     </span><span style="color:#008080;">*</span><span style="color:#800000;">+</span><span style="color:#C0C0C0;">     standing on the side of the road.
     |      
&gt; </span><span style="color: #FFFFFF; background: #0000FF">l tree
</span><span style="color:#C0C0C0;">                          </span><span style="color:#800080;">M</span><span style="color:#FFFF00;">E</span><span style="color:#000080;">R</span><span style="color:#800000;">R</span><span style="color:#008080;">Y</span><span style="color:#C0C0C0;">  </span><span style="color:#800080;">X</span><span style="color:#800000;">-</span><span style="color:#FFFF00;">M</span><span style="color:#008080;">A</span><span style="color:#000080;">S



</span><span style="color:#C0C0C0;">                               </span><span style="color:#FFFFFF;">*
</span><span style="color:#C0C0C0;">                              </span><span style="color:#008000;">***
</span><span style="color:#C0C0C0;">                             </span><span style="color:#800080;">@</span><span style="color:#008000;">***</span><span style="color:#008080;">@
</span><span style="color:#C0C0C0;">                           </span><span style="color:#FFFF00;">@</span><span style="color:#008000;">***</span><span style="color:#000080;">@</span><span style="color:#008000;">***</span><span style="color:#800080;">@
</span><span style="color:#C0C0C0;">                         </span><span style="color:#800000;">@</span><span style="color:#008000;">***********</span><span style="color:#008080;">@
</span><span style="color:#C0C0C0;">                      </span><span style="color:#000080;">@</span><span style="color:#008000;">*****</span><span style="color:#800080;">@</span><span style="color:#008000;">***********</span><span style="color:#FFFF00;">@
</span><span style="color:#C0C0C0;">                    </span><span style="color:#008080;">@</span><span style="color:#008000;">****</span><span style="color:#C0C0C0;">@</span><span style="color:#008000;">*******</span><span style="color:#000080;">@</span><span style="color:#008000;">*</span><span style="color:#800000;">@</span><span style="color:#008000;">******</span><span style="color:#800080;">@
</span><span style="color:#C0C0C0;">                         </span><span style="color:#800000;">@</span><span style="color:#008000;">***********</span><span style="color:#008080;">@
</span><span style="color:#C0C0C0;">                      </span><span style="color:#FFFF00;">@</span><span style="color:#008000;">*******</span><span style="color:#008080;">@</span><span style="color:#008000;">*********</span><span style="color:#FFFF00;">@
</span><span style="color:#C0C0C0;">                   </span><span style="color:#800080;">@</span><span style="color:#008000;">***</span><span style="color:#000080;">@</span><span style="color:#008000;">********************</span><span style="color:#C0C0C0;">@
                 </span><span style="color:#008080;">@</span><span style="color:#008000;">***</span><span style="color:#C0C0C0;">@</span><span style="color:#008000;">******</span><span style="color:#FFFF00;">@</span><span style="color:#008000;">*********</span><span style="color:#C0C0C0;">@</span><span style="color:#008000;">********</span><span style="color:#000080;">@
</span><span style="color:#C0C0C0;">              @</span><span style="color:#008000;">****</span><span style="color:#000080;">@</span><span style="color:#008000;">*******</span><span style="color:#800080;">@</span><span style="color:#008000;">*******</span><span style="color:#FFFF00;">@</span><span style="color:#008000;">**************</span><span style="color:#800000;">@
</span><span style="color:#C0C0C0;">                             |||||||
                             |||||||
                        =================
                         \              /
                          \            /
                           \          /
                            ==========</span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption">Festive...</p>
</article>

<?php /*
Template:
<article>
<p class="dwquote"><a id="log0" class="docanchor"></a>
<?php $this->placeholder('dwq')->captureStart('SET'); ?>
<span class="dwq_"></span>
<?php $this->placeholder('dwq')->captureEnd(); ?>
<?php echo str_replace("  ", "&nbsp;&nbsp;", nl2br($this->placeholder('dwq'))) ?>
</p>
<p class="dwcaption"></p>
</article>
*/ ?>

<?php echo $this->partial("last-mod-time.phtml", array("filename"=>__FILE__)) ?>
