<article class="portfoliosite">
    <h3><a href="http://www.web2messenger.com/">Web2Messenger — http://www.web2messenger.com/</a></h3>
    <p><img src="<?php echo $this->baseUrl() ?>/img/portfolio/w2m.png" alt="Web2Messenger Screenshot" width="200" height="179">Web2Messenger is a joint project with a Dutch contact of mine that allows users to receive anonymous messages from their own Web sites directly to their .NET Messenger Service client such as MSN Messenger or Windows Messenger.  As of October 2006 there are over 10,000 registered users of Web2Messenger.  The server-side code is PHP utilising Smarty and MySQL with the client-side code being a mix of XHTML 1.0 Transitional, CSS and JavaScript, and a RSS feed is available.  Web2Messenger has also been translated into Spanish, French and Portuguese and the language of the whole Web site can be changed instantly and updated easily if necessary.</p>
    <p>Unfortunately Web2Messenger is currently offline for a short period of time while it is moved to a new Web server. Hopefully this situation will be remedied very shortly.</p>
</article>

<section class="portfoliosite">
    <h3><a href="http://www.lorddeath.net/">Lord d'Eath's Stuff — http://www.lorddeath.net/</a></h3>
    <p><img src="<?php echo $this->baseUrl() ?>/img/portfolio/lds.png" alt="Lord d'Eath's Stuff Screenshot" width="200" height="135">This site is my own personal blog site and is a combination of a repository of tutorials that I have written, an on-line diary of my life and the Web site I use to experiment with new techniques.  As usual it uses PHP, Smarty, MySQL, XHTML 1.1, CSS and some JavaScript.  A nice touch is that the main page's content scrolls independent of the menus at the top and to the right, so the menu is always easily accessible.</p>
    <p>More recently I have improved the site for search engines with some Search Engine Optimisation (SEO) techniques, such as using standard filesystem URLs to replace more complex HTTP query strings, for example http://www.lorddeath.net/?page=blog becomes http://www.lorddeath.net/Blog/.</p>
</section>
    
<section class="portfoliosite">
    <h3><a href="http://www.udcx.com/">Unofficial Dark Century: X — http://www.udcx.com/</a></h3>
    <p><img src="<?php echo $this->baseUrl() ?>/img/portfolio/udcx.png" alt="uDCX Screenshot" width="200" height="202">A fan-site for an on-line Role-Playing Game (RPG) I enjoy, Neverwinter Nights, uDCX is primarily a collection of guides and other such documents and as such doesn't use MySQL very much, but the standard PHP, XHTML 1.0, CSS, JavaScript combination is still employed.  Unlike the two above projects uDCX does not use Smarty.  Web sites which contain a lot of black or other dark colours are fairly uncommon due to the connotations of "evil" that often accompanies such hues but black was a suitable colour to use in this case, mainly due to the name — Dark Century: X — but also because it helps set the mood of the game.  A game involving fantastical monsters whose sole aim is to kill your character would not be suited to "happier" blues and greens. uDCX and Web2Messenger are two projects that I have worked on as part of a team.</p>
</section>

<section class="portfoliosite">
    <h3><a href="http://www.udcx.com/GMaps/">Google Maps API-powered uDCX Maps — http://www.udcx.com/GMaps/</a></h3>
    <p><img src="<?php echo $this->baseUrl() ?>/img/portfolio/udcxgm.png" alt="uDCX Maps Screenshot" width="200" height="133">An extension to the above site is this map of the DC:X game-world which is powered by the Google Maps API. Using the API itself and creating the interactivity of the rest of the page vastly improved my JavaScript knowledge as well as allowing me to learn how to utilise the Google Maps API itself.</p>
</section>

<section class="portfoliosite">
    <h3><a href="http://www.lorddeath.net/filedb/">SubSonic File DB — http://www.lorddeath.net/filedb/</a></h3>
    <p><img src="<?php echo $this->baseUrl() ?>/img/portfolio/fdb.png" alt="SubSonic File DB Screenshot" width="200" height="155">Still in development, this file download database system has been designed to allow Web site owners to easily create a catalogue of downloadable files with categories, a file rating system, per-category and global RSS feeds, and file comments, as well as being fast and as easy as possible to control.</p>
</section>

<section class="portfoliosite">
    <h3>Lord d'Eath's RSS Aggregator &ndash; (no absolute URL — hosted and accessed locally)</h3>
    <p><img src="<?php echo $this->baseUrl() ?>/img/portfolio/rss.png" alt="RSS Aggregator Screenshot" width="200" height="118">This is not a Web site in the strictest sense but more of an experiment that I did to learn more about RSS and user interfaces.  I was unable to find an RSS aggregator program that suited my needs so I created one myself.  A Windows Scheduled Task runs every hour and calls a PHP script that fetches the RSS feeds of various Web sites of my choosing and updates the back-end MySQL database to reflect any changes to the RSS feeds.  I can then visit the aggregator's front-end which runs on a locally installed Apache Web server and read the updated articles.  Due to the prominent use of HTML frames in this system Smarty is not used as the processing overhead would be too great</p>
</section>