<aside class="cvdl">
    <p>This document is also available to download as a <span class="sprite-sites-docx"><a href="<?php echo $this->baseUrl() ?>/files/Andrew_Gillard_CV_Web.docx">Microsoft Word 2003 (.docx) file</a></span> or an <span class="sprite-sites-pdf"><a href="<?php echo $this->baseUrl() ?>/files/Andrew_Gillard_CV_Web.pdf">Adobe PDF (.pdf) file</a></span>.</p>
</aside>

<article class="cv">
    <h3>Personal Details</h3>
    <p class="cvcentre"><strong>Andrew Gillard</strong></p>
    <p class="cvcentre">Date of Birth: 7<sup>th</sup> February 1987</p>

    <table class="cvcontacttable">
        <tbody>
            <tr>
                <td>
                    <span class="cvredacted">Postal address<br>redacted from<br>Web copy</span>
                </td>
                <td>
                    cv@andrewgillard.com<br>
                    <span class="cvredacted">Phone numbers redacted<br>from Web copy</span><br>
                    Nationality: British
                </td>
            </tr>
        </tbody>
    </table>


    <h3>Education</h3>
    <p>I am currently a student at the University of Glamorgan, Pontypridd, studying a BSc (Hons) Computer Studies degree.  My level one results are:</p>
    <table class="cvqualificationtable">
        <tbody>
            <tr>
                <th>Computer Programming</th><td>92</td>
                <th>Introduction to Multimedia &amp; the Web</th><td>62</td>
            </tr>
            <tr>
                <th>Information Resource Engineering</th><td>73</td>
                <th>Mathematics and Statistics for Computing</th><td>73</td>
            </tr>
            <tr>
                <th>Professional and Business Skills</th><td>70</td>
                <th>Computer Systems and Internet Technology</th><td>74</td>
            </tr>
        </tbody>
    </table>

    <p>The following qualifications were achieved at Uckfield Community Technology College, East Sussex:</p>
    <table class="cvqualificationtable">
        <tbody>
            <tr>
                <th rowspan="3">A-Level (June 2005)</th>
                <th>Computing (AQA)</th><td>A</td>
            </tr>
            <tr>
                <th>Electronics (AQA)</th><td>A</td>
            </tr>
            <tr>
                <th>Physics (Edexcel)</th><td>D</td>
            </tr>
            
            <tr>
                <th>AS-Level (June 2004)</th>
                <th>Mathematics (AQA)</th><td>D</td>
            </tr>
            
            <tr>
                <th>GCSE (June 2002-2003)</th>
                <th colspan="2">11 GCSEs including A in Mathematics and C in English</th>
            </tr>
            
            <tr>
                <th>Other (January 1999)</th>
                <th>RSA Initial Text Processing (OCR)</th>
                <td>Distinction</td>
            </tr>
        </tbody>
    </table>


    <h3>Technical Skills</h3>
    <p>I am extremely proficient in PHP, and have used it to produce a number of websites.  In addition I have developed file maintenance utilities in the form of PHP shell scripts.  Most of my Web projects use MySQL and I can write fairly complex SQL queries to achieve whatever is required.  I am also very skilled in XHTML and CSS, with all of my code conforming to the W3C XHTML 1.1 and other relevant standards.  Additionally I can use JavaScript for XHTML form validation and fairly advanced page manipulation.  My most recent Web projects have utilised the Smarty template engine for easy and fast separation of the site's design and back-end PHP code and as such I have gained considerable experience using it.  I also try to embrace new technologies, for example placing an RSS feed on sites which would find it beneficial and I have utilised the Google Maps API and written reasonably complex JavaScript functions to complement it.</p>

    <p>More recently I have been learning Java and Visual Basic .NET and therefore have some understanding of these languages.</p>

    <p>Windows is my operating system of choice and I am an experienced user of both the Explorer shell and the command line interface.  My Web development background, however, has also given me some experience with UNIX-like systems (e.g. Linux).</p>

    <p>My favourite PHP editor is Zend Development Environment and I prefer to edit HTML, JavaScript and CSS in it, rather than using WYSIWYG HTML editors.  That said I used Macromedia Dreamweaver for at least a year before using Zend Development Environment and Microsoft Frontpage before that, and so I also know how to use those packages.  Most of my image editing work is done in Corel Paint Shop Pro X.</p>


    <h3>Web Site Development Portfolio</h3>
    <p>I have made available on my Web site a portfolio of some of the Web sites that I have either made myself or been part of the development team.  The URL to this portfolio is <a href="http://www.andrewgillard.com/portfolio">http://www.andrewgillard.com/portfolio</a>.</p>


    <h3>Work Experience</h3>
    <p>In 2002 as part of my Media Studies GCSE course I, along with three other students from my course, spent one week on the set of a film being shot in my home town called Neil's Party.  Our roles there were limited to making the tea and coffee for the cast and crew, cleaning and a small amount of set creation – painting etc. - but I still came away with valuable experience of the workplace as well as some interesting knowledge of the creation of films.</p>

    <p>Since then I have not had any fixed, official employment, but I have created a large number of PHP scripts for a friend – who is the owner of SubSonicSolutions Ltd. and an employee of Its Elixir (UK) Ltd. – often for payment.  Examples of scripts that I have written for him include an automated site backup script with GZip compression and FTP transfer, and a Content Management System (CMS).</p>

    <p>I have also had limited experience as a volunteer technical support assistant for the popular MSN Messenger add-on, Messenger Plus!, and spent a couple of hours every day in its IRC channel helping users who had difficulties using the product or had other questions. I did this for approximately a year until my educational commitments took a higher priority.</p>


    <h3>Hobbies</h3>
    <p>In my free time I enjoy talking to people on IRC, playing computer games, reading books, especially those from Terry Pratchett's Discworld series, watching the Stargate SG-1 and Stargate Atlantis TV series, and collecting and painting Games Workshop miniatures. While I don't actually use my miniatures in games any longer I still enjoy collecting and painting some of the more unique models as I find it provides a nice break from the computer.</p>


    <h3>Academic Reference</h3>
    <table class="cvcontacttable">
        <tbody>
            <tr>
                <td>
                    Geneen Stubbs,<br>
                    University of Glamorgan,<br>
                    Pontypridd,<br>
                    CF37 1DL
                </td>
            </tr>
        </tbody>
    </table>


    <h3>Work References</h3>
    <table class="cvcontacttable">
        <tbody>
            <tr>
                <td>
                    Craig Brass,<br>
                    Its Elixir,<br>
                    43a Millbrook Road,<br>
                    Kingstown Industrial Estate,<br>
                    Carlisle,<br>
                    CA3 0EU
                </td>
                <td>
                    Craig Brass,<br>
                    SubSonicSolutions,<br>
                    43b Millbrook Road,<br>
                    Kingstown Industrial Estate,<br>
                    Carlisle,<br>
                    CA3 0EU
                </td>
            </tr>
        </tbody>
    </table>
</article>
