<?php if (Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOption('lookingForWork')): ?>
    <article class="availableforwork">
        <p>I'm currently available for full-time, permanent work as an experienced, Zend Certified, Web Developer. If you're interested in hiring me, please email me at <a href="mailto:cv@andrewgillard.com">cv@andrewgillard.com</a>.</p>
    </article>
<?php endif; ?>

<aside class="cvdl">
    <p>This document is also available to download as a <span class="sprite-sites-docx"><a href="<?php echo $this->baseUrl() ?>/files/Andrew_Gillard_CV_Web.doc">Microsoft Word (.doc) file</a></span> or an <span class="sprite-sites-pdf"><a href="<?php echo $this->baseUrl() ?>/files/Andrew_Gillard_CV_Web.pdf">Adobe PDF (.pdf) file</a></span>.</p>
</aside>

<article class="cv">
    <div class="cvwidth">
        <h3 class="cvtitle">Andrew Gillard</h3>
        <h3>Personal Details</h3>
        <table class="cvcontacttable">
            <tbody>
                <tr>
                    <td>
                        <span class="cvredacted">Postal address<br> redacted from<br> Web copy</span>
                    </td>
                    <td>
                        <ul>
                            <li><a href="http://www.andrewgillard.com/portfolio/">http://www.andrewgillard.com/portfolio/</a></li>
                            <li><a href="mailto:cv@andrewgillard.com">cv@andrewgillard.com</a></li>
                            <li><span class="cvredacted">Phone number redacted<br> from Web copy</span></li>
                            <li>Date of Birth: 7<sup>th</sup> February 1987</li>
                            <li>Full, clean, UK driving licence with own car</li>
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>


        <h3>Work Experience</h3>
        <h4>Craig Brass Systems Ltd. – Lead Web Developer – 2007-2012</h4>
        <ul>
            <li>Responsible for choice of tools & libraries used in projects</li>
            <li>Designed overall architecture of software projects</li>
            <li>Designed large, complex relational database schemas</li>
            <li>Implemented majority of functionality of projects</li>
            <li>Created a base graphical design (HTML/CSS) for a dedicated graphic designer to work from</li>
            <li>Managed small team of developers (inc. reviewing code for style, stability and security requirements)</li>
            <li>Created extensive PHP framework (150+ classes; wide range of reusable features)</li>
        </ul>
        <h4>Miscellaneous</h4>
        <p>I have also had limited experience as a volunteer technical support assistant for the popular MSN Messenger add-on, Messenger Plus!, and spent a couple of hours every day in its IRC channel helping users who had difficulties using the product or had other questions. I did this for approximately a year until my educational commitments took a higher priority.</p>
        
        
        <h3>Certification</h3>
        <ul>
            <li>Zend Certified Engineer (PHP 5) – Candidate ID <a href="http://www.zend.com/zce.php?c=ZEND014075&amp;r=235816419">ZEND014075</a> – <em class="cvsubtle">June 2010</em></li>
        </ul>


        <h3>Education</h3>
        <h4>University of Glamorgan<span class="cveducationdates">October 2005 – June 2009</span></h4>
        <table class="cvqualificationtable">
            <tbody>
                <tr>
                    <th>Computer Studies</th>
                    <th>BSc (Hons)</th>
                    <td>First Class</td>
                </tr>
            </tbody>
        </table>

        <h4>Uckfield Community Technology College<span class="cveducationdates">September 2003 – June 2005</span></h4>
        <table class="cvqualificationtable">
            <tbody>
                <tr>
                    <th rowspan="3">A-Level (June 2005)</th>
                    <th>Computing (AQA)</th><td>A</td>
                </tr>
                <tr>
                    <th>Electronics (AQA)</th><td>A</td>
                </tr>
                <tr>
                    <th>Physics (Edexcel)</th><td>D</td>
                </tr>
                
                <tr class="border">
                    <th>AS-Level (June 2004)</th>
                    <th>Mathematics (AQA)</th><td>D</td>
                </tr>
            </tbody>
        </table>


        <h3>Technical Skills</h3>
        <h4>Web Development</h4>
        <p>Very proficient with:</p>
        <ul>
            <li>PHP (mostly PHP 5.3; PDO, SPL, full OOP; both Web and shell/daemon use)</li>
            <li>MySQL (normalisation; transactions; relational constraints)</li>
            <li>HTML (XHTML 1.1, HTML 5; fully-compliant, accessible and semantic; all hand-written, no WYSIWYG editors used)</li>
            <li>HTML 5 (FileReader; offline Web apps; geolocation)</li>
            <li>Mobile website development (for Android, iOS, etc.)</li>
            <li>CSS (including CSS 3)</li>
            <li>JavaScript (with and without jQuery and jQuery UI; Ajax; JSON)</li>
        </ul>
        <p>Also experienced with:</p>
        <ul>
            <li>Smarty</li>
            <li>Zend Framework</li>
            <li>Apache (mod_rewrite, other modules; general configuration)</li>
            <li>SOAP; XML</li>
            <li>APIs (Twitter, Flickr, YouTube, Facebook, Last.fm, ReCAPTCHA, Google Maps, Sitemaps)</li>
            <li>Payment gateway integration (PayPal, Google Checkout, WorldPay, NoChex, etc.)</li>
        </ul>
        
        <h4>Other Programming Experience</h4>
        <ul>
            <li>Java (including Android device development)</li>
            <li>Visual Basic .NET and C# .NET</li>
            <li>C++ (with and without Qt)</li>
            <li>Bash scripts; NWScript</li>
        </ul>
        
        <h4>Development Tools</h4>
        <ul>
            <li>IDEs (PhpED, Zend Studio, Eclipse, Visual Studio)</li>
            <li>Version control systems (Subversion, Git, Mercurial)</li>
        </ul>
        
        <h4>System Administration</h4>
        <ul>
            <li>Windows (7, XP; Server 2003, 2008)</li>
            <li>Linux (Ubuntu, Ubuntu Server; CentOS)</li>
        </ul>


        <h3>Hobbies</h3>
        <p>In my free time I can usually be found on a handful of IRC networks, playing Xbox 360 games, reading books – especially Terry Pratchett’s Discworld series – or watching TV.  During the summer months I spend a great deal of time in my garden tending to the plants and harvesting the fruit, which is something that I find both enjoyable and relaxing.  The garden also provides a perfect opportunity for me to indulge one of my other interests: photography.  Lately I have also been making improvements to the open source IRC client that I use on my Android phone and have had code merged into the upstream repository where it can benefit a wider audience.</p>


        <h3>Work Reference</h3>
        <h4>Craig Brass Systems Ltd.</h4>
        <p>Contact details available upon request.</p>
    </div>
</article>

<?php echo $this->partial("last-mod-time.phtml", array("filename"=>__FILE__)) ?>
